// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.AccessoryGroup;
import java.io.Serializable;

privileged aspect AccessoryGroup_Roo_Serializable {
    
    declare parents: AccessoryGroup implements Serializable;
    
    private static final long AccessoryGroup.serialVersionUID = 1L;
    
}
