// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.BrandIdentifier;
import java.io.Serializable;

privileged aspect BrandIdentifier_Roo_Serializable {
    
    declare parents: BrandIdentifier implements Serializable;
    
    private static final long BrandIdentifier.serialVersionUID = 1L;
    
}
