// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.CategoryAttributeRejectionFilter;
import java.util.List;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CategoryAttributeRejectionFilter_Roo_Jpa_ActiveRecord {
    
    public static long CategoryAttributeRejectionFilter.countCategoryAttributeRejectionFilters() {
        return entityManager().createQuery("SELECT COUNT(o) FROM CategoryAttributeRejectionFilter o", Long.class).getSingleResult();
    }
    
    public static List<CategoryAttributeRejectionFilter> CategoryAttributeRejectionFilter.findAllCategoryAttributeRejectionFilters() {
        return entityManager().createQuery("SELECT o FROM CategoryAttributeRejectionFilter o", CategoryAttributeRejectionFilter.class).getResultList();
    }
    
    public static CategoryAttributeRejectionFilter CategoryAttributeRejectionFilter.findCategoryAttributeRejectionFilter(Long id) {
        if (id == null) return null;
        return entityManager().find(CategoryAttributeRejectionFilter.class, id);
    }
    
    public static List<CategoryAttributeRejectionFilter> CategoryAttributeRejectionFilter.findCategoryAttributeRejectionFilterEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM CategoryAttributeRejectionFilter o", CategoryAttributeRejectionFilter.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public CategoryAttributeRejectionFilter CategoryAttributeRejectionFilter.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        CategoryAttributeRejectionFilter merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
