// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.Department;
import java.io.Serializable;

privileged aspect Department_Roo_Serializable {
    
    declare parents: Department implements Serializable;
    
    private static final long Department.serialVersionUID = 1L;
    
}
