// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.ItemVideo;
import java.io.Serializable;

privileged aspect ItemVideo_Roo_Serializable {
    
    declare parents: ItemVideo implements Serializable;
    
    private static final long ItemVideo.serialVersionUID = 1L;
    
}
