// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.MerchantOffer;
import java.io.Serializable;

privileged aspect MerchantOffer_Roo_Serializable {
    
    declare parents: MerchantOffer implements Serializable;
    
    private static final long MerchantOffer.serialVersionUID = 1L;
    
}
