// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.PrimaryColor;
import java.io.Serializable;

privileged aspect PrimaryColor_Roo_Serializable {
    
    declare parents: PrimaryColor implements Serializable;
    
    private static final long PrimaryColor.serialVersionUID = 1L;
    
}
