// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.ProductDetailPart;
import java.io.Serializable;

privileged aspect ProductDetailPart_Roo_Serializable {
    
    declare parents: ProductDetailPart implements Serializable;
    
    private static final long ProductDetailPart.serialVersionUID = 1L;
    
}
