// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.VideoType;
import java.io.Serializable;

privileged aspect VideoType_Roo_Serializable {
    
    declare parents: VideoType implements Serializable;
    
    private static final long VideoType.serialVersionUID = 1L;
    
}
