
-- SELECT '{"list":['

SET SESSION group_concat_max_len = 2000000;

SELECT
GROUP_CONCAT(
REPLACE(
CONCAT(
'{"nm":"',v.ProductModelName,'",',
'"lcl":"en_US",',
'"tp":"PRODUCT",',
'"tld":"',IFNULL(v.CribID,'null'),'",',
'"rlnm":"',v.URLName,'",',
IF(v.objectID IS NOT NULL,CONCAT('"id":"',v.objectID,'",'),'"id": null,'),
'"sbttrs":[',
'{"ky":"Brand", "vl":"',IFNULL(v.Brand,'null'),'"},',
'{"ky":"ProductModelName", "vl":"',IFNULL(v.ProductModelName,'null'),'"},',
'{"ky":"ListPrice", "vl":',IFNULL(v.ListPrice,0.00),'},',
getLowestPriceInfo(11,v.CribID),',',
'{"ky":"ProductImageUrl", "vl":"',IFNULL(getDefaultProductImage(11,v.CribID),'null'),'"}',
'],',
'"ctgry":',getCategory(11),',',
'"wnr":',getOwner(11,v.BrandID),',',
'"clrs":[',IFNULL(getProductImages(11,v.CribID),''),'],',
IF(getProductPurchaseInfo(11,v.CribID) IS NOT NULL,CONCAT('"mrchnts":[',getProductPurchaseInfo(11,v.CribID),'],'),''),
'"strs":[',IFNULL(getStrs(11,v.CribID),''),'],',
'"attrs":[',
'{"ky":"ColorCount", "vl":"',IFNULL(getProductColorCount(11,v.CribID),'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"Manufacturer", "vl":"',11),'{"ky":"Manufacturer", "vl":"'),IFNULL(v.Manufacturer,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ProductModelName", "vl":"',11),'{"ky":"ProductModelName", "vl":"'),IFNULL(v.ProductModelName,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ModelNumber", "vl":"',11),'{"ky":"ModelNumber", "vl":"'),IFNULL(v.ModelNumber,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ProductImageUrl", "vl":"',11),'{"ky":"ProductImageUrl", "vl":"'),IFNULL(getDefaultProductImage(11,v.CribID),'null'),'"},',
'{"ky":"CribTypeStandard", "vl":"',IFNULL(v.CribTypeStandard,'null'),'"},',
'{"ky":"CribTypePortable", "vl":"',IFNULL(v.CribTypePortable,'null'),'"},',
'{"ky":"CribTypeTravel", "vl":"',IFNULL(v.CribTypeTravel,'null'),'"},',
'{"ky":"CribTypeSpaceSaver", "vl":"',IFNULL(v.CribTypeSpaceSaver,'null'),'"},',
'{"ky":"CribTypeMultifunctional", "vl":"',IFNULL(v.CribTypeMultifunctional,'null'),'"},',
'{"ky":"CribTypeGrowsWithChild", "vl":"',IFNULL(v.CribTypeGrowsWithChild,'null'),'"},',
IF(v.SummaryCribType IS NOT NULL,CONCAT(getProductDetailGroups('{"ky":"SummaryCribType_1", "vl":"',11),v.SummaryCribType,'"},'),''),
IF(v.SummaryCribType IS NOT NULL,CONCAT(getProductDetailGroups('{"ky":"SummaryCribType_2", "vl":"',11),v.SummaryCribType,'"},'),''),
IF(v.SummaryCribType IS NOT NULL,CONCAT(getProductDetailGroups('{"ky":"SummaryCribType_3", "vl":"',11),v.SummaryCribType,'"},'),''),
'{"ky":"DesignStyleTraditional", "vl":"',IFNULL(v.DesignStyleTraditional,'null'),'"},',
'{"ky":"DesignStyleModern", "vl":"',IFNULL(v.DesignStyleModern,'null'),'"},',
'{"ky":"DesignStyleVintage", "vl":"',IFNULL(v.DesignStyleVintage,'null'),'"},',
'{"ky":"DesignStyleWhimsical", "vl":"',IFNULL(v.DesignStyleWhimsical,'null'),'"},',
'{"ky":"DesignStyleLuxury", "vl":"',IFNULL(v.DesignStyleLuxury,'null'),'"},',
'{"ky":"PrefAllWoodConstruction", "vl":"',IFNULL(v.PrefAllWoodConstruction,'null'),'"},',
'{"ky":"PrefIronOtherMetals", "vl":"',IFNULL(v.PrefIronOtherMetals,'null'),'"},',
'{"ky":"PrefContemporaryMetals", "vl":"',IFNULL(v.PrefContemporaryMetals,'null'),'"},',
'{"ky":"PrefECOFriendly", "vl":"',IFNULL(v.PrefECOFriendly,'null'),'"},',
'{"ky":"PrefSleigh", "vl":"',IFNULL(v.PrefSleigh,'null'),'"},',
'{"ky":"PrefMission", "vl":"',IFNULL(v.PrefMission,'null'),'"},',
'{"ky":"PrefJennyLind", "vl":"',IFNULL(v.PrefJennyLind,'null'),'"},',
'{"ky":"PrefCanopy", "vl":"',IFNULL(v.PrefCanopy,'null'),'"},',
'{"ky":"PrefRaisedEnds", "vl":"',IFNULL(v.PrefRaisedEnds,'null'),'"},',
'{"ky":"PrefCastors", "vl":"',IFNULL(v.PrefCastors,'null'),'"},',
'{"ky":"ColorWhite", "vl":"',IFNULL(v.ColorWhite,'null'),'"},',
'{"ky":"ColorDarkBrown", "vl":"',IFNULL(v.ColorDarkBrown,'null'),'"},',
'{"ky":"ColorLightBrown", "vl":"',IFNULL(v.ColorLightBrown,'null'),'"},',
'{"ky":"ColorNatural", "vl":"',IFNULL(v.ColorNatural,'null'),'"},',
'{"ky":"ColorOtherColor", "vl":"',IFNULL(v.ColorOtherColor,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ProductOverview", "vl":"',11),'{"ky":"ProductOverview", "vl":"'),IFNULL(REPLACE(REPLACE(v.ProductOverview,'     ',''),'"','inch'),'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BBBrandRating", "vl":"',11),'{"ky":"BBBrandRating", "vl":"'),IFNULL(v.BBBrandRating,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BBModelRecommended", "vl":"',11),'{"ky":"BBModelRecommended", "vl":"'),IFNULL(v.BBModelRecommended,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"GigglesListed", "vl":"',11),'{"ky":"GigglesListed", "vl":"'),IFNULL(v.GigglesListed,'null'),'"},',        
IFNULL(getProductDetailGroups('{"ky":"BrandCelebrityOwned", "vl":"',11),'{"ky":"BrandCelebrityOwned", "vl":"'),IFNULL(v.BrandCelebrityOwned,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BrandPromise", "vl":"',11),'{"ky":"BrandPromise", "vl":"'),IFNULL(v.BrandPromise,'null'),'"},',        
IFNULL(getProductDetailGroups('{"ky":"CollectionOrModelPromise", "vl":"',11),'{"ky":"CollectionOrModelPromise", "vl":"'),IFNULL(v.CollectionOrModelPromise,'null'),'"},',        
IFNULL(getProductDetailGroups('{"ky":"DesignStyle", "vl":"',11),'{"ky":"DesignStyle", "vl":"'),IFNULL(v.DesignStyle,'null'),'"},',                
IFNULL(getProductDetailGroups('{"ky":"SoldExclusivelyAt", "vl":"',11),'{"ky":"SoldExclusivelyAt", "vl":"'),IFNULL(v.SoldExclusivelyAt,'null'),'"},',                        
IFNULL(getProductDetailGroups('{"ky":"OtherRetailOutlets", "vl":"',11),'{"ky":"OtherRetailOutlets", "vl":"'),IFNULL(v.OtherRetailOutlets,'null'),'"},',                                
IFNULL(getProductDetailGroups('{"ky":"AvailableAmazon", "vl":"',11),'{"ky":"AvailableAmazon", "vl":"'),IFNULL(v.AvailableAmazon,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ASIN", "vl":"',11),'{"ky":"ASIN", "vl":"'),IFNULL(ASIN,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CountryOfManufacturer", "vl":"',11),'{"ky":"CountryOfManufacturer", "vl":"'),IFNULL(v.CountryOfManufacturer,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"JPMACertified", "vl":"',11),'{"ky":"JPMACertified", "vl":"'),IFNULL(v.JPMACertified,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CSPIACompiance", "vl":"',11),'{"ky":"CSPIACompiance", "vl":"'),IFNULL(v.CSPIACompiance,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CPSC1219_1220", "vl":"',11),'{"ky":"CPSC1219_1220", "vl":"'),IFNULL(v.CPSC1219_1220,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CPSC1130Reg", "vl":"',11),'{"ky":"CPSC1130Reg", "vl":"'),IFNULL(v.CPSC1130Reg,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CPSC1303LeadTest", "vl":"',11),'{"ky":"CPSC1303LeadTest", "vl":"'),IFNULL(v.CPSC1303LeadTest,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ASTMCert", "vl":"',11),'{"ky":"ASTMCert", "vl":"'),IFNULL(v.ASTMCert,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"FSCCert", "vl":"',11),'{"ky":"FSCCert", "vl":"'),IFNULL(v.FSCCert,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"SORCert", "vl":"',11),'{"ky":"SORCert", "vl":"'),IFNULL(v.SORCert,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CHPACompliance", "vl":"',11),'{"ky":"CHPACompliance", "vl":"'),IFNULL(v.CHPACompliance,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"GreenguardCert", "vl":"',11),'{"ky":"GreenguardCert", "vl":"'),IFNULL(v.GreenguardCert,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"SafetyCertification", "vl":"',11),'{"ky":"SafetyCertification", "vl":"'),IFNULL(v.SafetyCertification,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CRTested", "vl":"',11),'{"ky":"CRTested", "vl":"'),IFNULL(v.CRTested,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CROverallScore", "vl":"',11),'{"ky":"CROverallScore", "vl":"'),IFNULL(v.CROverallScore,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CRSafety", "vl":"',11),'{"ky":"CRSafety", "vl":"'),IFNULL(v.CRSafety,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CRConstruction", "vl":"',11),'{"ky":"CRConstruction", "vl":"'),IFNULL(v.CRConstruction,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CREaseOfUse", "vl":"',11),'{"ky":"CREaseOfUse", "vl":"'),IFNULL(v.CREaseOfUse,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CRComments", "vl":"',11),'{"ky":"CRComments", "vl":"'),IFNULL(v.CRComments,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CRSummary", "vl":"',11),'{"ky":"CRSummary", "vl":"'),IFNULL(v.CRSummary,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CRPROS", "vl":"',11),'{"ky":"CRPROS", "vl":"'),IFNULL(v.CRPROS,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CRCONS", "vl":"',11),'{"ky":"CRCONS", "vl":"'),IFNULL(CRCONS,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"RecallEvent", "vl":"',11),'{"ky":"RecallEvent", "vl":"'),IFNULL(RecallEvent,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"RecallURL", "vl":"',11),'{"ky":"RecallURL", "vl":"'),IFNULL(RecallURL,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"RecallDate", "vl":"',11),'{"ky":"RecallDate", "vl":"'),IFNULL(RecallDate,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"RecallUnits", "vl":"',11),'{"ky":"RecallUnits", "vl":"'),IFNULL(RecallUnits,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"RecallHazard", "vl":"',11),'{"ky":"RecallHazard", "vl":"'),IFNULL(RecallHazard,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"RecallIncidents", "vl":"',11),'{"ky":"RecallIncidents", "vl":"'),IFNULL(RecallIncidents,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"RecallSeverity", "vl":"',11),'{"ky":"RecallSeverity", "vl":"'),IFNULL(RecallSeverity,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"StationarySides", "vl":"',11),'{"ky":"StationarySides", "vl":"'),IFNULL(StationarySides,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"TeethingRail", "vl":"',11),'{"ky":"TeethingRail", "vl":"'),IFNULL(TeethingRail,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"FinishLowToxicity", "vl":"',11),'{"ky":"FinishLowToxicity", "vl":"'),IFNULL(FinishLowToxicity,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"Portable", "vl":"',11),'{"ky":"Portable", "vl":"'),IFNULL(Portable,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"Canopy", "vl":"',11),'{"ky":"Canopy", "vl":"'),IFNULL(Canopy,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"HeadAndFootBoards", "vl":"',11),'{"ky":"HeadAndFootBoards", "vl":"'),IFNULL(HeadAndFootBoards,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"MattressSupport", "vl":"',11),'{"ky":"MattressSupport", "vl":"'),IFNULL(MattressSupport,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"AdjustableMattressHeight", "vl":"',11),'{"ky":"AdjustableMattressHeight", "vl":"'),IFNULL(AdjustableMattressHeight,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ColorsAllWhite", "vl":"',11),'{"ky":"ColorsAllWhite", "vl":"'),IFNULL(ColorsAllWhite,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ColorsDarkBrown", "vl":"',11),'{"ky":"ColorsDarkBrown", "vl":"'),IFNULL(ColorsDarkBrown,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ColorsMediumBrown", "vl":"',11),'{"ky":"ColorsMediumBrown", "vl":"'),IFNULL(ColorsMediumBrown,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ColorsLightBrown", "vl":"',11),'{"ky":"ColorsLightBrown", "vl":"'),IFNULL(ColorsLightBrown,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ColorsTan", "vl":"',11),'{"ky":"ColorsTan", "vl":"'),IFNULL(ColorsTan,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ColorsOther", "vl":"',11),'{"ky":"ColorsOther", "vl":"'),IFNULL(ColorsOther,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"TotalColors", "vl":"',11),'{"ky":"TotalColors", "vl":"'),IFNULL(TotalColors,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ManufacturerColors", "vl":"',11),'{"ky":"ManufacturerColors", "vl":"'),IFNULL(ManufacturerColors,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"DimensionsInches_W", "vl":"',11),'{"ky":"DimensionsInches_W", "vl":"'),IFNULL(DimensionsInches_W,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"DimensionsInches_L", "vl":"',11),'{"ky":"DimensionsInches_L", "vl":"'),IFNULL(DimensionsInches_L,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"DimensionsInches_H", "vl":"',11),'{"ky":"DimensionsInches_H", "vl":"'),IFNULL(DimensionsInches_H,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"DimensionsInches_WLH", "vl":"',11),'{"ky":"DimensionsInches_WLH", "vl":"'),IFNULL(v.DimensionsInches_WLH,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CribShape", "vl":"',11),'{"ky":"CribShape", "vl":"'),IFNULL(CribShape,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CribCapacity", "vl":"',11),'{"ky":"CribCapacity", "vl":"'),IFNULL(CribCapacity,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CompactFold", "vl":"',11),'{"ky":"CompactFold", "vl":"'),IFNULL(CompactFold,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"WoodType", "vl":"',11),'{"ky":"WoodType", "vl":"'),IFNULL(WoodType,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"MaterialsType", "vl":"',11),'{"ky":"MaterialsType", "vl":"'),IFNULL(MaterialsType,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"AssemblyLevel", "vl":"',11),'{"ky":"AssemblyLevel", "vl":"'),IFNULL(AssemblyLevel,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CribDesignStyle", "vl":"',11),'{"ky":"CribDesignStyle", "vl":"'),IFNULL(CribDesignStyle,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"GrowsWithChild", "vl":"',11),'{"ky":"GrowsWithChild", "vl":"'),IFNULL(GrowsWithChild,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ConversionType", "vl":"',11),'{"ky":"ConversionType", "vl":"'),IFNULL(ConversionType,'null'),'"},',
IF(BassinetIncluded IS NOT NULL,CONCAT(getProductDetailGroupsAccessories(11,'{"ky":"BassinetIncluded", "vl":"',BassinetIncluded),BassinetIncludedAcc,'"},'),''),
IF(ChangingTableIncluded IS NOT NULL,CONCAT(getProductDetailGroupsAccessories(11,'{"ky":"ChangingTableIncluded", "vl":"',ChangingTableIncluded),ChangingTableIncludedAcc,'"},'),''),
IF(StorageIncluded IS NOT NULL,CONCAT(getProductDetailGroupsAccessories(11,'{"ky":"StorageIncluded", "vl":"',StorageIncluded),StorageIncludedAcc,'"},'),''),
IF(MattressIncluded IS NOT NULL,CONCAT(getProductDetailGroupsAccessories(11,'{"ky":"MattressIncluded", "vl":"',MattressIncluded),MattressIncludedAcc,'"},'),''),
IFNULL(getProductDetailGroups('{"ky":"HardwareVisible", "vl":"',11),'{"ky":"HardwareVisible", "vl":"'),IFNULL(HardwareVisible,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"AgeLimit", "vl":"',11),'{"ky":"AgeLimit", "vl":"'),IFNULL(AgeLimit,'null'),'"},',
'{"ky":"ListPrice", "vl":',IFNULL(v.ListPrice,0.00),'},',
getLowestPriceInfo(11,v.CribID),',',
IFNULL(getProductDetailGroups('{"ky":"ListPriceRange", "vl":"',11),'{"ky":"ListPriceRange", "vl":"'),IFNULL(ListPriceRange,'null'),'"},',
'{"ky":"SalePrice", "vl":',IFNULL(SalePrice,'null'),'},',
IFNULL(getProductDetailGroups('{"ky":"NewModelDiscount", "vl":"',11),'{"ky":"NewModelDiscount", "vl":"'),IFNULL(NewModelDiscount,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"SourceURLDiscountedModel", "vl":"',11),'{"ky":"SourceURLDiscountedModel", "vl":"'),IFNULL(SourceURLDiscountedModel,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ToddlerConversionPrice", "vl":"',11),'{"ky":"ToddlerConversionPrice", "vl":"'),IFNULL(ToddlerConversionPrice,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"TwinBedConversionPrice", "vl":"',11),'{"ky":"TwinBedConversionPrice", "vl":"'),IFNULL(TwinBedConversionPrice,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"FullBedConversionPrice", "vl":"',11),'{"ky":"FullBedConversionPrice", "vl":"'),IFNULL(FullBedConversionPrice,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"FacebookURL", "vl":"',11),'{"ky":"FacebookURL", "vl":"'),IFNULL(v.FacebookURL,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BrandFacebookLikes", "vl":"',11),'{"ky":"BrandFacebookLikes", "vl":"'),IFNULL(v.BrandFacebookLikes,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"TwitterName", "vl":"',11),'{"ky":"TwitterName", "vl":"'),IFNULL(v.TwitterName,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"TwitterURL", "vl":"',11),'{"ky":"TwitterURL", "vl":"'),IFNULL(v.TwitterURL,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BrandTwitterFollowers", "vl":"',11),'{"ky":"BrandTwitterFollowers", "vl":"'),IFNULL(v.BrandTwitterFollowers,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ResaleValue", "vl":"',11),'{"ky":"ResaleValue", "vl":"'),IFNULL(v.ResaleValue,'null'),'"}],','"mtvtrs" : {',
'"A":',IFNULL(m.A,0),',',
'"B":',IFNULL(m.B,0),',',
'"C":',IFNULL(m.C,0),',',
'"E":',IFNULL(m.E,0),',',
'"G":',IFNULL(m.G,0),',',
'"H":',IFNULL(m.H,0),',',
'"I":',IFNULL(m.I,0),',',
'"J":',IFNULL(m.J,0),',',
'"K":',IFNULL(m.K,0),',',
'"L":',IFNULL(m.L,0),'',
'}}'),'"null"','null')) AS payload   
FROM
  vw_cribs_data_ui v
JOIN vw_crib_motivators m
  ON v.CribID = m.ItemID AND
  m.CategoryID = v.CategoryID
WHERE v.CribID = 204
AND getDefaultProductImage(11,v.CribID) IS NOT NULL 
AND getLowestPriceInfo(11,v.CribID) IS NOT NULL

-- SELECT ']}'

