
-- SELECT '{"list":['

SET SESSION group_concat_max_len = 2000000;

SELECT
  GROUP_CONCAT(REPLACE(CONCAT('{"nm":"',v.ProductModelName, '",',
'"lcl":"en_US",',
'"tp":"PRODUCT",',
'"tld":"',IFNULL(v.StrollerID,'null'),'",',
'"rlnm":"',v.URLName,'",',
IF(v.objectID IS NOT NULL,CONCAT('"id":"',v.objectID,'",'),'"id": null,'),
'"sbttrs":[',
'{"ky":"Brand", "vl":"',IFNULL(v.Brand,'null'),'"},',
'{"ky":"ProductModelName", "vl":"',IFNULL(v.ProductModelName,'null'),'"},',
'{"ky":"ListPrice", "vl":',IFNULL(v.ListPrice,0.00),'},',
getLowestPriceInfo(2,v.StrollerID),',',
'{"ky":"ProductImageUrl", "vl":"',IFNULL(getDefaultProductImage(2,v.StrollerID),'null'),'"}',
'],',
'"ctgry":',getCategory(2),',', 
'"wnr":',getOwner(2,v.BrandID),',', 
'"clrs":[',IFNULL(getProductImages(2,v.StrollerID),''),'],',
IF(getProductPurchaseInfo(2,v.StrollerID) IS NOT NULL,CONCAT('"mrchnts":[',getProductPurchaseInfo(2,v.StrollerID),'],'),''),
'"strs":[',IFNULL(getStrs(2,v.StrollerID),''),'],',
'"attrs":[',
'{"ky":"ColorCount", "vl":"',IFNULL(getProductColorCount(2,v.StrollerID),'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"Manufacturer", "vl":"',2),'{"ky":"Manufacturer", "vl":"'),IFNULL(v.Manufacturer,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ProductModelName", "vl":"',2),'{"ky":"ProductModelName", "vl":"'),IFNULL(v.ProductModelName,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ProductModelNo", "vl":"',2),'{"ky":"ProductModelNo", "vl":"'),IFNULL(v.ProductModelNo,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ProductImageUrl", "vl":"',2),'{"ky":"ProductImageUrl", "vl":"'),IFNULL(getDefaultProductImage(2,v.StrollerID),'null'),'"},',
'{"ky":"ProductUrl", "vl":"',IFNULL(urlencode(getProductURL(v.Brand, v.ProductModelName)),'null'),'"},',
'{"ky":"BestForTallParents", "vl":"',IFNULL(v.BestForTallParents,'null'),'"},',
'{"ky":"BestForInfants", "vl":"',IFNULL(v.BestForInfants,'null'),'"},',
'{"ky":"BestForMultipleAgedChildren", "vl":"',IFNULL(v.BestForMultipleAgedChildren,'null'),'"},',
'{"ky":"BestForToddlersOlderKids", "vl":"',IFNULL(v.BestForToddlersOlderKids,'null'),'"},',
'{"ky":"BestForGrowingFamily", "vl":"',IFNULL(v.BestForGrowingFamily,'null'),'"},',
'{"ky":"BestForAirplaneTravel", "vl":"',IFNULL(v.BestForAirplaneTravel,'null'),'"},',
'{"ky":"BestForUrbanLiving", "vl":"',IFNULL(v.BestForUrbanLiving,'null'),'"},',
IF(v.BestForSummary IS NOT NULL,CONCAT(getProductDetailGroups('{"ky":"BestForSummary_1", "vl":"',2),BestForSummary,'"},'),''),  
IF(v.BestForSummary IS NOT NULL,CONCAT(getProductDetailGroups('{"ky":"BestForSummary_2", "vl":"',2),BestForSummary,'"},'),''),  
IF(v.BestForSummary IS NOT NULL,CONCAT(getProductDetailGroups('{"ky":"BestForSummary_3", "vl":"',2),BestForSummary,'"},'),''),  
'{"ky":"ThingsMatterModernStyle", "vl":"',IFNULL(v.ThingsMatterModernStyle,'null'),'"},',
'{"ky":"ThingsMatterSportyStyle", "vl":"',IFNULL(v.ThingsMatterSportyStyle,'null'),'"},',
'{"ky":"ThingsMatterInnovativeDesign", "vl":"',IFNULL(v.ThingsMatterInnovativeDesign,'null'),'"},',
'{"ky":"ThingsMatterLightweight", "vl":"',IFNULL(v.ThingsMatterLightweight,'null'),'"},',
'{"ky":"ThingsMatterEZManeuver", "vl":"',IFNULL(v.ThingsMatterEZManeuver,'null'),'"},',
'{"ky":"ThingsMatterCompact", "vl":"',IFNULL(v.ThingsMatterCompact,'null'),'"},',
IF(v.ThingsMatterSummary IS NOT NULL,CONCAT(getProductDetailGroups('{"ky":"ThingsMatterSummary_1", "vl":"',2),ThingsMatterSummary,'"},'),''),  
IF(v.ThingsMatterSummary IS NOT NULL,CONCAT(getProductDetailGroups('{"ky":"ThingsMatterSummary_2", "vl":"',2),ThingsMatterSummary,'"},'),''),  
IF(v.ThingsMatterSummary IS NOT NULL,CONCAT(getProductDetailGroups('{"ky":"ThingsMatterSummary_3", "vl":"',2),ThingsMatterSummary,'"},'),''),  
'{"ky":"',v.NumberSeatsFilter,'", "vl":"true"},',  
IFNULL(getProductDetailGroups('{"ky":"UPC", "vl":"',2),'{"ky":"UPC", "vl":"'),IFNULL(v.UPC,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"GTIN", "vl":"',2),'{"ky":"GTIN", "vl":"'),IFNULL(v.GTIN,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"Country", "vl":"',2),'{"ky":"Country", "vl":"'),IFNULL(v.Country,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"JPMACertified", "vl":"',2),'{"ky":"JPMACertified", "vl":"'),IFNULL(v.JPMACertified,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ASTMF833Tested", "vl":"',2),'{"ky":"ASTMF833Tested", "vl":"'),IFNULL(v.ASTMF833Tested,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"TUVTested", "vl":"',2),'{"ky":"TUVTested", "vl":"'),IFNULL(v.TUVTested,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"EN1888Tested", "vl":"',2),'{"ky":"EN1888Tested", "vl":"'),IFNULL(v.EN1888Tested,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"SOR85_379Tested", "vl":"',2),'{"ky":"SOR85_379Tested", "vl":"'),IFNULL(v.SOR85_379Tested,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CPSIA2008Tested", "vl":"',2),'{"ky":"CPSIA2008Tested", "vl":"'),IFNULL(v.CPSIA2008Tested,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"SafetyCertification", "vl":"',2),'{"ky":"SafetyCertification", "vl":"'),IFNULL(v.SafetyCertification,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ConsumerReportsRated", "vl":"',2),'{"ky":"ConsumerReportsRated", "vl":"'),IFNULL(v.ConsumerReportsRated,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CRSafety", "vl":"',2),'{"ky":"CRSafety", "vl":"'),IFNULL(v.CRSafety,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"RecallEvent", "vl":"',2),'{"ky":"RecallEvent", "vl":"'),IFNULL(v.RecallEvent,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"RecallDate", "vl":"',2),'{"ky":"RecallDate", "vl":"'),IFNULL(v.RecallDate,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"RecallUnits", "vl":"',2),'{"ky":"RecallUnits", "vl":"'),IFNULL(v.RecallUnits,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"RecallHazard", "vl":"',2),'{"ky":"RecallHazard", "vl":"'),IFNULL(v.RecallHazard,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"RecallIncidentsInjuries", "vl":"',2),'{"ky":"RecallIncidentsInjuries", "vl":"'),IFNULL(v.RecallIncidentsInjuries,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"RecallSeverity", "vl":"',2),'{"ky":"RecallSeverity", "vl":"'),IFNULL(v.RecallSeverity,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"StrollerTypeTraditional", "vl":"',2),'{"ky":"StrollerTypeTraditional", "vl":"'),IFNULL(StrollerTypeTraditional,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"StrollerTypeMultiFunction", "vl":"',2),'{"ky":"StrollerTypeMultiFunction", "vl":"'),IFNULL(StrollerTypeMultiFunction,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"StrollerTypePrams", "vl":"',2),'{"ky":"StrollerTypePrams", "vl":"'),IFNULL(StrollerTypePrams,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"StrollerTypeLightwtUmbrella", "vl":"',2),'{"ky":"StrollerTypeLightwtUmbrella", "vl":"'),IFNULL(StrollerTypeLightwtUmbrella,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"StrollerTypeJogging", "vl":"',2),'{"ky":"StrollerTypeJogging", "vl":"'),IFNULL(StrollerTypeJogging,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"StrollerTypeAllTerrain", "vl":"',2),'{"ky":"StrollerTypeAllTerrain", "vl":"'),IFNULL(StrollerTypeAllTerrain,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"StrollerTypeMultiple", "vl":"',2),'{"ky":"StrollerTypeMultiple", "vl":"'),IFNULL(StrollerTypeMultiple,'null'),'"},',
IF(SummaryStrollerType IS NOT NULL,CONCAT(getProductDetailGroups('{"ky":"SummaryStrollerType_1", "vl":"',2),SummaryStrollerType,'"},'),''),  
IF(SummaryStrollerType IS NOT NULL,CONCAT(getProductDetailGroups('{"ky":"SummaryStrollerType_2", "vl":"',2),SummaryStrollerType,'"},'),''),  
IF(SummaryStrollerType IS NOT NULL,CONCAT(getProductDetailGroups('{"ky":"SummaryStrollerType_3", "vl":"',2),SummaryStrollerType,'"},'),''),  
IF(v.NumberSeats IS NOT NULL,CONCAT(getProductDetailGroups('{"ky":"NumberSeats", "vl":"',2),NumberSeats,'"},'),''),  
IFNULL(getProductDetailGroups('{"ky":"Multiplekids", "vl":"',2),'{"ky":"Multiplekids", "vl":"'),IFNULL(v.Multiplekids,'null'),'"},',
IF(v.FootBoardPrice IS NOT NULL,CONCAT(getProductDetailGroupsAccessories(2,'{"ky":"FootBoardPrice", "vl":"',FootBoardPrice),v.FootBoardPriceAcc,'"},'),''),
IF(v.JoggerConversionPrice IS NOT NULL,CONCAT(getProductDetailGroupsAccessories(2,'{"ky":"JoggerConversionPrice", "vl":"',JoggerConversionPrice),v.JoggerConversionPrice,'"},'),''),
IFNULL(getProductDetailGroups('{"ky":"NewbornToToddler", "vl":"',2),'{"ky":"NewbornToToddler", "vl":"'),IFNULL(v.NewbornToToddler,'null'),'"},',
IF(v.Bassinet IS NOT NULL,CONCAT(getProductDetailGroupsAccessories(2,'{"ky":"Bassinet", "vl":"',Bassinet),v.BassinetAcc,'"},'),''),
IFNULL(getProductDetailGroups('{"ky":"BassinetPrice", "vl":"',2),'{"ky":"BassinetPrice", "vl":"'),IFNULL(v.BassinetPrice,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BassinetAdaptorPrice", "vl":"',2),'{"ky":"BassinetAdaptorPrice", "vl":"'),IFNULL(v.BassinetAdaptorPrice,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"RecliningSeat", "vl":"',2),'{"ky":"RecliningSeat", "vl":"'),IFNULL(v.RecliningSeat,'null'),'"},',
IF(v.CarSeatAdaptable IS NOT NULL,CONCAT(getProductDetailGroupsAccessories(2,'{"ky":"CarSeatAdaptable", "vl":"',CarSeatAdaptable),v.CarSeatAdaptableAcc,'"},'),''),
IFNULL(getProductDetailGroups('{"ky":"NumberOfCarSeatBrands", "vl":"',2),'{"ky":"NumberOfCarSeatBrands", "vl":"'),IFNULL(v.NumberOfCarSeatBrands,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"NumberOfCarSeatModels", "vl":"',2),'{"ky":"NumberOfCarSeatModels", "vl":"'),IFNULL(v.NumberOfCarSeatModels,'null'),'"},',
IF(v.CarSeatLists IS NOT NULL,CONCAT(getProductDetailGroups('{"ky":"CarSeatLists", "vl":"',2),v.CarSeatLists,'"},'),''),
IFNULL(getProductDetailGroups('{"ky":"WeightLbs", "vl":"',2),'{"ky":"WeightLbs", "vl":"'),IFNULL(v.WeightLbs,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"MaximumWeightOfChildLbs", "vl":"',2),'{"ky":"MaximumWeightOfChildLbs", "vl":"'),IFNULL(v.MaximumWeightOfChildLbs,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"DimensionsInchesFull_W", "vl":"',2),'{"ky":"DimensionsInchesFull_W", "vl":"'),IFNULL(v.DimensionsInchesFull_W,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"DimensionsInchesFull_D", "vl":"',2),'{"ky":"DimensionsInchesFull_D", "vl":"'),IFNULL(v.DimensionsInchesFull_D,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"DimensionsInchesFull_H", "vl":"',2),'{"ky":"DimensionsInchesFull_H", "vl":"'),IFNULL(v.DimensionsInchesFull_H,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"DimensionsInchesFull_HWD", "vl":"',2),'{"ky":"DimensionsInchesFull_HWD", "vl":"'),IFNULL(v.DimensionsInchesFull_HWD,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"DimensionsInchesFolded_W", "vl":"',2),'{"ky":"DimensionsInchesFolded_W", "vl":"'),IFNULL(v.DimensionsInchesFolded_W,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"DimensionsInchesFolded_D", "vl":"',2),'{"ky":"DimensionsInchesFolded_D", "vl":"'),IFNULL(v.DimensionsInchesFolded_D,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"DimensionsInchesFolded_H", "vl":"',2),'{"ky":"DimensionsInchesFolded_H", "vl":"'),IFNULL(v.DimensionsInchesFolded_H,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"DimensionsInchesFolded_HWD", "vl":"',2),'{"ky":"DimensionsInchesFolded_HWD", "vl":"'),IFNULL(v.DimensionsInchesFolded_HWD,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"FoldType", "vl":"',2),'{"ky":"FoldType", "vl":"'),IFNULL(v.FoldType,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ReplaceableFabric", "vl":"',2),'{"ky":"ReplaceableFabric", "vl":"'),IFNULL(v.ReplaceableFabric,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"MachineWashable", "vl":"',2),'{"ky":"MachineWashable", "vl":"'),IFNULL(v.MachineWashable,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ListPriceRange", "vl":"',2),'{"ky":"ListPriceRange", "vl":"'),IFNULL(v.ListPriceRange,'null'),'"},',
'{"ky":"ListPrice", "vl":',IFNULL(v.ListPrice,0.00),'},',
getLowestPriceInfo(2,v.StrollerID),',',
IFNULL(getProductDetailGroups('{"ky":"SalePrice", "vl":"',2),'{"ky":"SalePrice", "vl":"'),IFNULL(v.SalePrice,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"NewModelDiscount", "vl":"',2),'{"ky":"NewModelDiscount", "vl":"'),IFNULL(v.NewModelDiscount,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ResaleValue", "vl":"',2),'{"ky":"ResaleValue", "vl":"'),IFNULL(v.ResaleValue,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"NumberOfColorsOrPatternsAvailableNeon", "vl":"',2),'{"ky":"NumberOfColorsOrPatternsAvailableNeon", "vl":"'),IFNULL(v.NumberOfColorsOrPatternsAvailableNeon,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"NumberOfColorsOrPatternsAvailableVeryBrightOrPrimary", "vl":"',2),'{"ky":"NumberOfColorsOrPatternsAvailableVeryBrightOrPrimary", "vl":"'),IFNULL(v.NumberOfColorsOrPatternsAvailableVeryBrightOrPrimary,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"NumberOfColorsOrPatternsAvailableNeutralEarthTones", "vl":"',2),'{"ky":"NumberOfColorsOrPatternsAvailableNeutralEarthTones", "vl":"'),IFNULL(v.NumberOfColorsOrPatternsAvailableNeutralEarthTones,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"NumberOfColorsOrPatternsAvailableDeepBluePurples", "vl":"',2),'{"ky":"NumberOfColorsOrPatternsAvailableDeepBluePurples", "vl":"'),IFNULL(v.NumberOfColorsOrPatternsAvailableDeepBluePurples,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"NumberOfColorsOrPatternsAvailableGrayOrBlack", "vl":"',2),'{"ky":"NumberOfColorsOrPatternsAvailableGrayOrBlack", "vl":"'),IFNULL(v.NumberOfColorsOrPatternsAvailableGrayOrBlack,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ManufacturerColor", "vl":"',2),'{"ky":"ManufacturerColor", "vl":"'),IFNULL(v.ManufacturerColor,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"RearForwardFacing", "vl":"',2),'{"ky":"RearForwardFacing", "vl":"'),IFNULL(v.RearForwardFacing,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"FrontWheelMaterial", "vl":"',2),'{"ky":"FrontWheelMaterial", "vl":"'),IFNULL(v.FrontWheelMaterial,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"FrontWheelType", "vl":"',2),'{"ky":"FrontWheelType", "vl":"'),IFNULL(v.FrontWheelType,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BackWheelMaterial", "vl":"',2),'{"ky":"BackWheelMaterial", "vl":"'),IFNULL(v.BackWheelMaterial,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BackWheelType", "vl":"',2),'{"ky":"BackWheelType", "vl":"'),IFNULL(v.BackWheelType,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"AdjustableHandle", "vl":"',2),'{"ky":"AdjustableHandle", "vl":"'),IFNULL(v.AdjustableHandle,'null'),'"},',
IF(v.AdultCupHolder IS NOT NULL,CONCAT(getProductDetailGroupsAccessories(2,'{"ky":"AdultCupHolder", "vl":"',AdultCupHolder),v.AdultCupHolderAcc,'"},'),''),
IFNULL(getProductDetailGroups('{"ky":"AdultCupHolderPrice", "vl":"',2),'{"ky":"AdultCupHolderPrice", "vl":"'),IFNULL(v.AdultCupHolderPrice,'null'),'"},',
IF(v.ChildsFoodTray IS NOT NULL,CONCAT(getProductDetailGroupsAccessories(2,'{"ky":"ChildsFoodTray", "vl":"',ChildsFoodTray),v.ChildsFoodTrayAcc,'"},'),''),
IFNULL(getProductDetailGroups('{"ky":"ChildsFoodTrayPrice", "vl":"',2),'{"ky":"ChildsFoodTrayPrice", "vl":"'),IFNULL(v.ChildsFoodTrayPrice,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CushionedOrPaddedSeat", "vl":"',2),'{"ky":"CushionedOrPaddedSeat", "vl":"'),IFNULL(v.CushionedOrPaddedSeat,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CanopyType", "vl":"',2),'{"ky":"CanopyType", "vl":"'),IFNULL(v.CanopyType,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"PeekabooWindow", "vl":"',2),'{"ky":"PeekabooWindow", "vl":"'),IFNULL(v.PeekabooWindow,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"LegRest", "vl":"',2),'{"ky":"LegRest", "vl":"'),IFNULL(v.LegRest,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"FootRest", "vl":"',2),'{"ky":"FootRest", "vl":"'),IFNULL(v.FootRest,'null'),'"},',
IF(v.InfantHeadRest IS NOT NULL,CONCAT(getProductDetailGroupsAccessories(2,'{"ky":"InfantHeadRest", "vl":"',InfantHeadRest),v.InfantHeadRestAcc,'"},'),''),
IFNULL(getProductDetailGroups('{"ky":"ShoulderPads", "vl":"',2),'{"ky":"ShoulderPads", "vl":"'),IFNULL(v.ShoulderPads,'null'),'"},',
IF(v.RainProtection IS NOT NULL,CONCAT(getProductDetailGroupsAccessories(2,'{"ky":"RainProtection", "vl":"',RainProtection),v.RainProtectionAcc,'"},'),''),
IFNULL(getProductDetailGroups('{"ky":"RainProtectionPrice", "vl":"',2),'{"ky":"RainProtectionPrice", "vl":"'),IFNULL(v.RainProtectionPrice,'null'),'"},',
IF(v.UVProtection IS NOT NULL,CONCAT(getProductDetailGroupsAccessories(2,'{"ky":"UVProtection", "vl":"',UVProtection),v.UVProtectionAcc,'"},'),''),
IFNULL(getProductDetailGroups('{"ky":"UVProtectionPrice", "vl":"',2),'{"ky":"UVProtectionPrice", "vl":"'),IFNULL(v.UVProtectionPrice ,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"StorageBasket", "vl":"',2),'{"ky":"StorageBasket", "vl":"'),IFNULL(v.StorageBasket,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"Harness", "vl":"',2),'{"ky":"Harness", "vl":"'),IFNULL(v.Harness,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"OneTouchBrakesFoot", "vl":"',2),'{"ky":"OneTouchBrakesFoot", "vl":"'),IFNULL(v.OneTouchBrakesFoot,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"OneTouchBrakesHand", "vl":"',2),'{"ky":"OneTouchBrakesHand", "vl":"'),IFNULL(v.OneTouchBrakesHand,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CREaseOfUse", "vl":"',2),'{"ky":"CREaseOfUse", "vl":"'),IFNULL(v.CREaseOfUse,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CRManeuverability", "vl":"',2),'{"ky":"CRManeuverability", "vl":"'),IFNULL(v.CRManeuverability,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CRFoldedSize", "vl":"',2),'{"ky":"CRFoldedSize", "vl":"'),IFNULL(v.CRFoldedSize,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BestUses", "vl":"',2),'{"ky":"BestUses", "vl":"'),IFNULL(v.BestUses,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"Extras", "vl":"',2),'{"ky":"Extras", "vl":"'),IFNULL(v.Extras,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ProductOverview", "vl":"',2),'{"ky":"ProductOverview", "vl":"'),IFNULL(REPLACE(v.ProductOverview,'     ',''),'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"FacebookURL", "vl":"',2),'{"ky":"FacebookURL", "vl":"'),IFNULL(v.FacebookURL,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BrandFacebookLikes", "vl":"',2),'{"ky":"BrandFacebookLikes", "vl":"'),IFNULL(v.FacebookLikes,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"TwitterName", "vl":"',2),'{"ky":"TwitterName", "vl":"'),IFNULL(v.TwitterName,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"TwitterURL", "vl":"',2),'{"ky":"TwitterURL", "vl":"'),IFNULL(v.TwitterURL,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BrandTwitterFollowers", "vl":"',2),'{"ky":"BrandTwitterFollowers", "vl":"'),IFNULL(v.TwitterFollowers,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BabiesRUSTopSelling", "vl":"',2),'{"ky":"BabiesRUSTopSelling", "vl":"'),IFNULL(v.BabiesRUSTopSelling,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BabyGagaParentRating", "vl":"',2),'{"ky":"BabyGagaParentRating", "vl":"'),IFNULL(v.BabyGagaParentRating,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BabyBargainsRating", "vl":"',2),'{"ky":"BabyBargainsRating", "vl":"'),IFNULL(v.BabyBargainsRating,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BabyGagaDurability", "vl":"',2),'{"ky":"BabyGagaDurability", "vl":"'),IFNULL(v.BabyGagaDurability,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"NAPPARecipient", "vl":"',2),'{"ky":"NAPPARecipient", "vl":"'),IFNULL(v.NAPPARecipient,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"JPMARecipient", "vl":"',2),'{"ky":"JPMARecipient", "vl":"'),IFNULL(v.JPMARecipient,'null'),'"},',
IF(LENGTH(v.Awards) <> 0,CONCAT(getProductDetailGroups('{"ky":"Awards", "vl":"',2),v.Awards,'"},'),''),
IFNULL(getProductDetailGroups('{"ky":"CROverallScore", "vl":"',2),'{"ky":"CROverallScore", "vl":"'),IFNULL(v.CROverallScore,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CRComment", "vl":"',2),'{"ky":"CRComment", "vl":"'),IFNULL(v.CRComment,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BabiesRUsParentRating", "vl":"',2),'{"ky":"BabiesRUsParentRating", "vl":"'),IFNULL(v.BabiesRUsParentRating,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"DesignStyle", "vl":"',2),'{"ky":"DesignStyle", "vl":"'),IFNULL(v.DesignStyle,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"MediaSpotlight", "vl":"',2),'{"ky":"MediaSpotlight", "vl":"'),IFNULL(v.MediaSpotlight,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CelebritySightings", "vl":"',2),'{"ky":"CelebritySightings", "vl":"'),IFNULL(v.CelebritySightings,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"GiggleListed", "vl":"',2),'{"ky":"GiggleListed", "vl":"'),IFNULL(v.GiggleListed,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BabbleRecognition", "vl":"',2),'{"ky":"BabbleRecognition", "vl":"'),IFNULL(v.BabbleRecognition,'null'),'"},',
IF(LENGTH(v.YouTubeVideoID_1) <> 0,CONCAT('{"ky":"YouTubeVideoID_1", "vl":"',v.YouTubeVideoID_1,'"},'),''),
IF(LENGTH(v.YouTubeVideoTitle_1) <> 0,CONCAT('{"ky":"YouTubeVideoTitle_1", "vl":"',v.YouTubeVideoTitle_1,'"},'),''),
IF(LENGTH(v.YouTubeVideoID_2) <> 0,CONCAT('{"ky":"YouTubeVideoID_2", "vl":"',v.YouTubeVideoID_2,'"},'),''),
IF(LENGTH(v.YouTubeVideoTitle_2) <> 0,CONCAT('{"ky":"YouTubeVideoTitle_2", "vl":"',v.YouTubeVideoTitle_2,'"},'),''),
IFNULL(getProductDetailGroups('{"ky":"BabyBargainsRecognition", "vl":"',2),'{"ky":"BabyBargainsRecognition", "vl":"'),IFNULL(v.BabyBargainsRecognition,'null'),'"}],',
'"mtvtrs" : {',
'"A":',IFNULL(m.A,0),',',
'"B":',IFNULL(m.B,0),',',
'"C":',IFNULL(m.C,0),',',
'"D":',IFNULL(m.D,0),',',
'"E":',IFNULL(m.E,0),',',
'"F":',IFNULL(m.F,0),',',
'"G":',IFNULL(m.G,0),',',
'"H":',IFNULL(m.H,0),',',
'"I":',IFNULL(m.I,0),',',
'"J":',IFNULL(m.J,0),',',
'"K":',IFNULL(m.K,0),',',
'"L":',IFNULL(m.L,0),'',
'}}'),'"null"','null')) AS payload   
FROM vw_stroller_data_ui v
JOIN vw_stroller_motivators m
 ON v.StrollerID = m.ItemID
 AND m.CategoryID = v.CategoryID
WHERE v.StrollerID = 73 -- 195
AND getDefaultProductImage(2,v.StrollerID) IS NOT NULL
AND getLowestPriceInfo(2,v.StrollerID) IS NOT NULL





