
-- SELECT '{"list":['

SET SESSION group_concat_max_len = 2000000;

SELECT 
  GROUP_CONCAT(REPLACE(CONCAT('{"nm":"',sd.ProductModelName, '",',
'"lcl":"en_US",',
'"tp":"PRODUCT",',
'"tld":"',IFNULL(sd.CarSeatID,'null'),'",',
'"rlnm":"',sd.URLName,'",',
IF(sd.objectID IS NOT NULL,CONCAT('"id":"',sd.objectID,'",'),'"id": null,'),
'"sbttrs":[',
'{"ky":"Brand", "vl":"',IFNULL(sd.Brand,'null'),'"},',
'{"ky":"ProductModelName", "vl":"',IFNULL(sd.ProductModelName,'null'),'"},',
'{"ky":"ListPrice", "vl":',IFNULL(CAST(REPLACE(ListPrice,'$','') AS DECIMAL(8,2)),'null'),'},',
getLowestPriceInfo(12,sd.CarSeatID),',',
'{"ky":"ProductImageUrl", "vl":"',IFNULL(getDefaultProductImage(12,sd.CarSeatID),'null'),'"}',
'],',
'"ctgry":',getCategory(12),',', 
'"wnr":',getOwner(12,sd.BrandID),',', 
'"clrs":[',IFNULL(getProductImages(12,sd.CarSeatID),''),'],',
IF(getProductPurchaseInfo(12,sd.CarSeatID) IS NOT NULL,CONCAT('"mrchnts":[',getProductPurchaseInfo(12,sd.CarSeatID),'],'),''),
'"strs":[',IFNULL(getStrs(12,sd.CarSeatID),''),'],',
'"attrs":[',
'{"ky":"ColorCount", "vl":"',IFNULL(getProductColorCount(12,sd.CarSeatID),'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"Manufacturer", "vl":"',12),'{"ky":"Manufacturer", "vl":"'),IFNULL(sd.Manufacturer,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ProductModelName", "vl":"',12),'{"ky":"ProductModelName", "vl":"'),IFNULL(sd.ProductModelName,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ModelNumber", "vl":"',12),'{"ky":"ModelNumber", "vl":"'),IFNULL(sd.ModelNumber,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CarSeatType", "vl":"',12),'{"ky":"CarSeatType", "vl":"'),IFNULL(sd.CarSeatType,'null'),'"},',
'{"ky":"CarSeatTypeBestForNewborns", "vl":"',IFNULL(sd.CarSeatTypeBestForNewborns,'null'),'"},',
'{"ky":"CarSeatTypeGrowsWithChild", "vl":"',IFNULL(sd.CarSeatTypeGrowsWithChild,'null'),'"},',
IF(sd.SummaryCarseatType IS NOT NULL,CONCAT(getProductDetailGroups('{"ky":"SummaryCarseatType_1", "vl":"',12),sd.SummaryCarseatType,'"},'),''),  
IF(sd.SummaryCarseatType IS NOT NULL,CONCAT(getProductDetailGroups('{"ky":"SummaryCarseatType_2", "vl":"',12),sd.SummaryCarseatType,'"},'),''),  
IF(sd.SummaryCarseatType IS NOT NULL,CONCAT(getProductDetailGroups('{"ky":"SummaryCarseatType_3", "vl":"',12),sd.SummaryCarseatType,'"},'),''),  
'{"ky":"FeatureStrollerCompatible", "vl":"',IFNULL(sd.FeatureStrollerCompatible,'null'),'"},',
'{"ky":"FeatureShockAbsorbingFoam", "vl":"',IFNULL(sd.FeatureShockAbsorbingFoam,'null'),'"},',
'{"ky":"FeatureBoot", "vl":"',IFNULL(sd.FeatureBoot,'null'),'"},',
'{"ky":"FeatureInfantHeadPillows", "vl":"',IFNULL(sd.FeatureInfantHeadPillows,'null'),'"},',
'{"ky":"FeatureBodyCushions", "vl":"',IFNULL(sd.FeatureBodyCushions,'null'),'"},',
'{"ky":"FeatureMachineWashableSeatCover", "vl":"',IFNULL(sd.FeatureMachineWashableSeatCover,'null'),'"},',
'{"ky":"FeatureCanopy", "vl":"',IFNULL(sd.FeatureCanopy,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CompatibleWithStroller", "vl":"',12),'{"ky":"CompatibleWithStroller", "vl":"'),IFNULL(sd.CompatibleWithStroller,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"DesignStyle", "vl":"',12),'{"ky":"DesignStyle", "vl":"'),IFNULL(sd.DesignStyle,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BBBrandRating", "vl":"',12),'{"ky":"BBBrandRating", "vl":"'),IFNULL(sd.BBBrandRating,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BBModelRecommended", "vl":"',12),'{"ky":"BBModelRecommended", "vl":"'),IFNULL(sd.BBModelRecommended,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"NHTSARated", "vl":"',12),'{"ky":"NHTSARated", "vl":"'),IFNULL(sd.NHTSARated,'null'),'"},',
IF(LENGTH(sd.SafetyCertification) <> 0,CONCAT(getProductDetailGroups('{"ky":"SafetyCertification", "vl":"',12),sd.SafetyCertification,'"},'),''),
IFNULL(getProductDetailGroups('{"ky":"NHTSAConvertibleTypeRating", "vl":"',12),'{"ky":"NHTSAConvertibleTypeRating", "vl":"'),IFNULL(sd.NHTSAConvertibleTypeRating,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"NHTSALabels", "vl":"',12),'{"ky":"NHTSALabels", "vl":"'),IFNULL(sd.NHTSALabels,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"NHTSAInstructions", "vl":"',12),'{"ky":"NHTSAInstructions", "vl":"'),IFNULL(sd.NHTSAInstructions,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"NHTSASecuringTheChild", "vl":"',12),'{"ky":"NHTSASecuringTheChild", "vl":"'),IFNULL(sd.NHTSASecuringTheChild,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"NHTSAInstallationFeatures", "vl":"',12),'{"ky":"NHTSAInstallationFeatures", "vl":"'),IFNULL(sd.NHTSAInstallationFeatures,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"NHSTAOverallEaseOfUse", "vl":"',12),'{"ky":"NHSTAOverallEaseOfUse", "vl":"'),IFNULL(sd.NHSTAOverallEaseOfUse,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BabbleRecomended", "vl":"',12),'{"ky":"BabbleRecomended", "vl":"'),IFNULL(sd.BabbleRecomended,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"GigglesListed", "vl":"',12),'{"ky":"GigglesListed", "vl":"'),IFNULL(sd.GigglesListed,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"AmazonBestseller", "vl":"',12),'{"ky":"AmazonBestseller", "vl":"'),IFNULL(sd.AmazonBestseller,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"AmazonRating", "vl":"',12),'{"ky":"AmazonRating", "vl":"'),IFNULL(sd.AmazonRating,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BabiesRUsBestseller", "vl":"',12),'{"ky":"BabiesRUsBestseller", "vl":"'),IFNULL(sd.BabiesRUsBestseller,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BabiesRUsTopRated", "vl":"',12),'{"ky":"BabiesRUsTopRated", "vl":"'),IFNULL(sd.BabiesRUsTopRated,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"NAPPAAwardWinner", "vl":"',12),'{"ky":"NAPPAAwardWinner", "vl":"'),IFNULL(sd.NAPPAAwardWinner,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"JPMAAwardWinner", "vl":"',12),'{"ky":"JPMAAwardWinner", "vl":"'),IFNULL(sd.JPMAAwardWinner,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"PTPAAwardWinner", "vl":"',12),'{"ky":"PTPAAwardWinner", "vl":"'),IFNULL(sd.PTPAAwardWinner,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"iParentingAwardWinner", "vl":"',12),'{"ky":"iParentingAwardWinner", "vl":"'),IFNULL(sd.iParentingAwardWinner,'null'),'"},',
IF(LENGTH(sd.Awards) <> 0,CONCAT(getProductDetailGroups('{"ky":"Awards", "vl":"',12),sd.Awards,'"},'),''),
IFNULL(getProductDetailGroups('{"ky":"BrandPromise", "vl":"',12),'{"ky":"BrandPromise", "vl":"'),IFNULL(REPLACE(sd.BrandPromise,'"',''),'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ModelPromise", "vl":"',12),'{"ky":"ModelPromise", "vl":"'),IFNULL(REPLACE(sd.ModelPromise,'"',''),'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ProductOverview", "vl":"',12),'{"ky":"ProductOverview", "vl":"'),IFNULL(REPLACE(sd.ProductOverview,'"',''),'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"AvailableAmazon", "vl":"',12),'{"ky":"AvailableAmazon", "vl":"'),IFNULL(sd.AvailableAmazon,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ASIN", "vl":"',12),'{"ky":"ASIN", "vl":"'),IFNULL(sd.ASIN,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CountryOfManufacturer", "vl":"',12),'{"ky":"CountryOfManufacturer", "vl":"'),IFNULL(sd.CountryOfManufacturer,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ShockAbsorbingFoam", "vl":"',12),'{"ky":"ShockAbsorbingFoam", "vl":"'),IFNULL(sd.ShockAbsorbingFoam,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"HarnessType", "vl":"',12),'{"ky":"HarnessType", "vl":"'),IFNULL(sd.HarnessType,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CRURL", "vl":"',12),'{"ky":"CRURL", "vl":"'),IFNULL(sd.CRURL,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CRTested", "vl":"',12),'{"ky":"CRTested", "vl":"'),IFNULL(sd.CRTested,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CROverallScore", "vl":"',12),'{"ky":"CROverallScore", "vl":"'),IFNULL(sd.CROverallScore,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CRCrashProtection", "vl":"',12),'{"ky":"CRCrashProtection", "vl":"'),IFNULL(sd.CRCrashProtection,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CREaseOfUse", "vl":"',12),'{"ky":"CREaseOfUse", "vl":"'),IFNULL(sd.CREaseOfUse,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CRLATCH", "vl":"',12),'{"ky":"CRLATCH", "vl":"'),IFNULL(sd.CRLATCH,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CRBELT", "vl":"',12),'{"ky":"CRBELT", "vl":"'),IFNULL(sd.CRBELT,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CRComments", "vl":"',12),'{"ky":"CRComments", "vl":"'),IFNULL(REPLACE(sd.CRComments,'"',''),'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CRSummary", "vl":"',12),'{"ky":"CRSummary", "vl":"'),IFNULL(REPLACE(sd.CRSummary,'"',''),'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CRPROS", "vl":"',12),'{"ky":"CRPROS", "vl":"'),IFNULL(REPLACE(sd.CRPROS,'"',''),'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CRCONS", "vl":"',12),'{"ky":"CRCONS", "vl":"'),IFNULL(REPLACE(sd.CRCONS,'"',''),'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"RecallEvent", "vl":"',12),'{"ky":"RecallEvent", "vl":"'),IFNULL(sd.RecallEvent,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"RecallURL", "vl":"',12),'{"ky":"RecallURL", "vl":"'),IFNULL(sd.RecallURL,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"RecallDate", "vl":"',12),'{"ky":"RecallDate", "vl":"'),IFNULL(sd.RecallDate,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"RecallUnits", "vl":"',12),'{"ky":"RecallUnits", "vl":"'),IFNULL(sd.RecallUnits,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"RecallHazard", "vl":"',12),'{"ky":"RecallHazard", "vl":"'),IFNULL(sd.RecallHazard,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"RecallIncidentsInjuries", "vl":"',12),'{"ky":"RecallIncidentsInjuries", "vl":"'),IFNULL(sd.RecallIncidentsInjuries,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"RecallSeverity", "vl":"',12),'{"ky":"RecallSeverity", "vl":"'),IFNULL(sd.RecallSeverity,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"NumberOfColorsNeon", "vl":"',12),'{"ky":"NumberOfColorsNeon", "vl":"'),IFNULL(sd.NumberOfColorsNeon,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"NumberOfColorsVeryBrightOrPrimary", "vl":"',12),'{"ky":"NumberOfColorsVeryBrightOrPrimary", "vl":"'),IFNULL(sd.NumberOfColorsVeryBrightOrPrimary,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"NumberOfColorsNeutralEarthTones", "vl":"',12),'{"ky":"NumberOfColorsNeutralEarthTones", "vl":"'),IFNULL(sd.NumberOfColorsNeutralEarthTones,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"NumberOfColorsDeepBluePurples", "vl":"',12),'{"ky":"NumberOfColorsDeepBluePurples", "vl":"'),IFNULL(sd.NumberOfColorsDeepBluePurples,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"NumberOfColorsGrayOrBlack", "vl":"',12),'{"ky":"NumberOfColorsGrayOrBlack", "vl":"'),IFNULL(sd.NumberOfColorsGrayOrBlack,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"TotalColors", "vl":"',12),'{"ky":"TotalColors", "vl":"'),IFNULL(sd.TotalColors,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ManufacturerColorNames", "vl":"',12),'{"ky":"ManufacturerColorNames", "vl":"'),IFNULL(sd.ManufacturerColorNames,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CarSeat_W", "vl":"',12),'{"ky":"CarSeat_W", "vl":"'),IFNULL(sd.CarSeat_W,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CarSeat_L", "vl":"',12),'{"ky":"CarSeat_L", "vl":"'),IFNULL(sd.CarSeat_L,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CarSeat_H", "vl":"',12),'{"ky":"CarSeat_H", "vl":"'),IFNULL(sd.CarSeat_H,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"DimensionsInches_WLH", "vl":"',12),'{"ky":"DimensionsInches_WLH", "vl":"'),IFNULL(sd.DimensionsInches_WLH,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CarrierWeight", "vl":"',12),'{"ky":"CarrierWeight", "vl":"'),IFNULL(sd.CarrierWeight,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ChildWeightLimit", "vl":"',12),'{"ky":"ChildWeightLimit", "vl":"'),IFNULL(sd.ChildWeightLimit,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ChildHeightLimit", "vl":"',12),'{"ky":"ChildHeightLimit", "vl":"'),IFNULL(sd.ChildHeightLimit,'null'),'"},',
IF(Boot IS NOT NULL,CONCAT(getProductDetailGroupsAccessories(12,'{"ky":"Boot", "vl":"',Boot),BootAcc,'"},'),''),
IFNULL(getProductDetailGroups('{"ky":"PlushPadding", "vl":"',12),'{"ky":"PlushPadding", "vl":"'),IFNULL(sd.PlushPadding,'null'),'"},',
IF(InfantHeadPillows IS NOT NULL,CONCAT(getProductDetailGroupsAccessories(12,'{"ky":"InfantHeadPillows", "vl":"',InfantHeadPillows),InfantHeadPillowsAcc,'"},'),''),
IF(BodyCushions IS NOT NULL,CONCAT(getProductDetailGroupsAccessories(12,'{"ky":"BodyCushions", "vl":"',BodyCushions),BodyCushionsAcc,'"},'),''),  
IFNULL(getProductDetailGroups('{"ky":"BreathableFabrics", "vl":"',12),'{"ky":"BreathableFabrics", "vl":"'),IFNULL(sd.BreathableFabrics,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"MachineWashableFabrics", "vl":"',12),'{"ky":"MachineWashableFabrics", "vl":"'),IFNULL(sd.MachineWashableFabrics,'null'),'"},',
IF(Canopy IS NOT NULL,CONCAT(getProductDetailGroupsAccessories(12,'{"ky":"Canopy", "vl":"',Canopy),CanopyAcc,'"},'),''),    
'{"ky":"ListPrice", "vl":',IFNULL(CAST(REPLACE(sd.ListPrice,'$','') AS DECIMAL(8,2)),'null'),'},',
getLowestPriceInfo(12,sd.CarSeatID),',',
IFNULL(getProductDetailGroups('{"ky":"ListPriceRange", "vl":"',12),'{"ky":"ListPriceRange", "vl":"'),IFNULL(sd.ListPriceRange,'null'),'"},',
'{"ky":"SalePrice", "vl":',IFNULL(CAST(REPLACE(sd.SalePrice,'$','') AS DECIMAL(8,2)),'null'),'},',
IFNULL(getProductDetailGroups('{"ky":"NewModelDiscount", "vl":"',12),'{"ky":"NewModelDiscount", "vl":"'),IFNULL(sd.NewModelDiscount,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"DiscountedModelSourceURL", "vl":"',12),'{"ky":"DiscountedModelSourceURL", "vl":"'),IFNULL(sd.DiscountedModelSourceURL,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"FacebookURL", "vl":"',12),'{"ky":"FacebookURL", "vl":"'),IFNULL(sd.FacebookURL,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BrandFacebookLikes", "vl":"',12),'{"ky":"BrandFacebookLikes", "vl":"'),IFNULL(sd.FacebookLikes,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"TwitterName", "vl":"',12),'{"ky":"TwitterName", "vl":"'),IFNULL(sd.TwitterName,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"TwitterURL", "vl":"',12),'{"ky":"TwitterURL", "vl":"'),IFNULL(sd.TwitterURL,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BrandTwitterFollowers", "vl":"',12),'{"ky":"BrandTwitterFollowers", "vl":"'),IFNULL(sd.TwitterFollowers,'null'),'"}],',
'"mtvtrs" : {',
'"A":',IFNULL(m.A,0),',',
'"B":',IFNULL(m.B,0),',',
'"C":',IFNULL(m.C,0),',',
'"E":',IFNULL(m.E,0),',',
'"F":',IFNULL(m.F,0),',',
'"G":',IFNULL(m.G,0),',',
'"H":',IFNULL(m.H,0),',',
'"I":',IFNULL(m.I,0),',',
'"J":',IFNULL(m.J,0),',',
'"K":',IFNULL(m.K,0),',',
'"L":',IFNULL(m.L,0),'',
'}}'),'"null"','null')) AS payload   
FROM vw_carseat_data_ui sd
JOIN vw_carseat_motivators m
  ON sd.CarseatID = m.ItemID AND
  m.CategoryID = sd.CategoryID
WHERE sd.CarseatID = 7
AND getDefaultProductImage(12,sd.CarSeatID) IS NOT NULL 
AND getLowestPriceInfo(12,sd.CarSeatID) IS NOT NULL

-- SELECT ']}'
