SET SESSION group_concat_max_len = 2000000;

SELECT 
  GROUP_CONCAT(REPLACE(CONCAT('{"nm":"',v.ProductModelName, '",',
'"lcl":"en_US",',
'"tp":"PRODUCT",',
'"tld":"',IFNULL(v.BabyMonitorID,'null'),'",',
'"rlnm":"',v.URLName,'",',
IF(v.objectID IS NOT NULL,CONCAT('"id":"',v.objectID,'",'),'"id": null,'),
'"sbttrs":[',
'{"ky":"Brand", "vl":"',IFNULL(v.Brand,'null'),'"},',
'{"ky":"ProductModelName", "vl":"',IFNULL(v.ProductModelName,'null'),'"},',
'{"ky":"ListPrice", "vl":',IFNULL(CAST(REPLACE(v.ListPrice,'$','') AS DECIMAL(8,2)),'null'),'},',
getLowestPriceInfo(14,v.BabyMonitorID),',',
'{"ky":"ProductImageUrl", "vl":"',IFNULL(getDefaultProductImage(14,v.BabyMonitorID),'null'),'"}',
'],',
'"ctgry":',getCategory(14),',', 
'"wnr":',getOwner(14,v.BrandID),',', 
'"clrs":[',IFNULL(getProductImages(14,v.BabyMonitorID),''),'],',
IF(getProductPurchaseInfo(14,v.BabyMonitorID) IS NOT NULL,CONCAT('"mrchnts":[',getProductPurchaseInfo(14,v.BabyMonitorID),'],'),''),
'"strs":[',IFNULL(getStrs(14,v.BabyMonitorID),''),'],',
'"attrs":[',
IFNULL(getProductDetailGroups('{"ky":"BabyMonitorID", "vl":"',14),'{"ky":"BabyMonitorID", "vl":"'),IFNULL(BabyMonitorID,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CategoryID", "vl":"',14),'{"ky":"CategoryID", "vl":"'),IFNULL(v.CategoryID,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"Brand", "vl":"',14),'{"ky":"Brand", "vl":"'),IFNULL(Brand,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BrandID", "vl":"',14),'{"ky":"BrandID", "vl":"'),IFNULL(BrandID,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"URLName", "vl":"',14),'{"ky":"URLName", "vl":"'),IFNULL(URLName,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"objectID", "vl":"',14),'{"ky":"objectID", "vl":"'),IFNULL(objectID,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"Manufacturer", "vl":"',14),'{"ky":"Manufacturer", "vl":"'),IFNULL(Manufacturer,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"Validated", "vl":"',14),'{"ky":"Validated", "vl":"'),IFNULL(Validated,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ProductModelName", "vl":"',14),'{"ky":"ProductModelName", "vl":"'),IFNULL(ProductModelName,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ModelNumber", "vl":"',14),'{"ky":"ModelNumber", "vl":"'),IFNULL(ModelNumber,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"MonitorType", "vl":"',14),'{"ky":"MonitorType", "vl":"'),IFNULL(MonitorType,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"MonitorTypeAudioOnly", "vl":"',14),'{"ky":"MonitorTypeAudioOnly", "vl":"'),IFNULL(MonitorTypeAudioOnly,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"MonitorTypeMovement", "vl":"',14),'{"ky":"MonitorTypeMovement", "vl":"'),IFNULL(MonitorTypeMovement,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"MonitorTypeVideo", "vl":"',14),'{"ky":"MonitorTypeVideo", "vl":"'),IFNULL(MonitorTypeVideo,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"SummaryMonitorType", "vl":"',14),'{"ky":"SummaryMonitorType", "vl":"'),IFNULL(SummaryMonitorType,'null'),'"},',
IF(SummaryMonitorType IS NOT NULL,CONCAT(getProductDetailGroups('{"ky":"SummaryMonitorType_1", "vl":"',14),SummaryMonitorType,'"},'),''),  
IF(SummaryMonitorType IS NOT NULL,CONCAT(getProductDetailGroups('{"ky":"SummaryMonitorType_2", "vl":"',14),SummaryMonitorType,'"},'),''),  
IF(SummaryMonitorType IS NOT NULL,CONCAT(getProductDetailGroups('{"ky":"SummaryMonitorType_3", "vl":"',14),SummaryMonitorType,'"},'),''),  
IFNULL(getProductDetailGroups('{"ky":"BestForAptLiving", "vl":"',14),'{"ky":"BestForAptLiving", "vl":"'),IFNULL(BestForAptLiving,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BestForLargeHome", "vl":"',14),'{"ky":"BestForLargeHome", "vl":"'),IFNULL(BestForLargeHome,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BestForMultipleChildren", "vl":"',14),'{"ky":"BestForMultipleChildren", "vl":"'),IFNULL(BestForMultipleChildren,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BestForWorkingParents", "vl":"',14),'{"ky":"BestForWorkingParents", "vl":"'),IFNULL(BestForWorkingParents,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BestForSummary", "vl":"',14),'{"ky":"BestForSummary", "vl":"'),IFNULL(BestForSummary,'null'),'"},',
IF(v.BestForSummary IS NOT NULL,CONCAT(getProductDetailGroups('{"ky":"BestForSummary_1", "vl":"',14),BestForSummary,'"},'),''),  
IF(v.BestForSummary IS NOT NULL,CONCAT(getProductDetailGroups('{"ky":"BestForSummary_2", "vl":"',14),BestForSummary,'"},'),''),  
IF(v.BestForSummary IS NOT NULL,CONCAT(getProductDetailGroups('{"ky":"BestForSummary_3", "vl":"',14),BestForSummary,'"},'),''),  
IFNULL(getProductDetailGroups('{"ky":"FeatureExtensiveRange", "vl":"',14),'{"ky":"FeatureExtensiveRange", "vl":"'),IFNULL(FeatureExtensiveRange,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"FeatureSecureConnection", "vl":"',14),'{"ky":"FeatureSecureConnection", "vl":"'),IFNULL(FeatureSecureConnection,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"FeatureLargeLCD", "vl":"',14),'{"ky":"FeatureLargeLCD", "vl":"'),IFNULL(FeatureLargeLCD,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"FeaturePanningZooming", "vl":"',14),'{"ky":"FeaturePanningZooming", "vl":"'),IFNULL(FeaturePanningZooming,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"FeatureMultiCameraViews", "vl":"',14),'{"ky":"FeatureMultiCameraViews", "vl":"'),IFNULL(FeatureMultiCameraViews,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"FeatureMultipleMPUs", "vl":"',14),'{"ky":"FeatureMultipleMPUs", "vl":"'),IFNULL(FeatureMultipleMPUs,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"FeatureMotionDetection", "vl":"',14),'{"ky":"FeatureMotionDetection", "vl":"'),IFNULL(FeatureMotionDetection,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"FeatureSoundActivation", "vl":"',14),'{"ky":"FeatureSoundActivation", "vl":"'),IFNULL(FeatureSoundActivation,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"FeatureLongBatteryLife", "vl":"',14),'{"ky":"FeatureLongBatteryLife", "vl":"'),IFNULL(FeatureLongBatteryLife,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"SavvyNetworkViewable", "vl":"',14),'{"ky":"SavvyNetworkViewable", "vl":"'),IFNULL(SavvyNetworkViewable,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"SavvySmartPhoneViewable", "vl":"',14),'{"ky":"SavvySmartPhoneViewable", "vl":"'),IFNULL(SavvySmartPhoneViewable,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"SavvyImageSharing", "vl":"',14),'{"ky":"SavvyImageSharing", "vl":"'),IFNULL(SavvyImageSharing,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"SavvyTouchMenu", "vl":"',14),'{"ky":"SavvyTouchMenu", "vl":"'),IFNULL(SavvyTouchMenu,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ComfortsPortable", "vl":"',14),'{"ky":"ComfortsPortable", "vl":"'),IFNULL(ComfortsPortable,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ComfortsTalkBack", "vl":"',14),'{"ky":"ComfortsTalkBack", "vl":"'),IFNULL(ComfortsTalkBack,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ComfortsColorVideo", "vl":"',14),'{"ky":"ComfortsColorVideo", "vl":"'),IFNULL(ComfortsColorVideo,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ComfortsNightVision", "vl":"',14),'{"ky":"ComfortsNightVision", "vl":"'),IFNULL(ComfortsNightVision,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ComfortsMusic", "vl":"',14),'{"ky":"ComfortsMusic", "vl":"'),IFNULL(ComfortsMusic,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ComfortsNightLight", "vl":"',14),'{"ky":"ComfortsNightLight", "vl":"'),IFNULL(ComfortsNightLight,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ComfortsTempDisplay", "vl":"',14),'{"ky":"ComfortsTempDisplay", "vl":"'),IFNULL(ComfortsTempDisplay,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"Priority", "vl":"',14),'{"ky":"Priority", "vl":"'),IFNULL(Priority,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BBBrandRating", "vl":"',14),'{"ky":"BBBrandRating", "vl":"'),IFNULL(BBBrandRating,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BBModelRecommended", "vl":"',14),'{"ky":"BBModelRecommended", "vl":"'),IFNULL(BBModelRecommended,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BabbleRecomended", "vl":"',14),'{"ky":"BabbleRecomended", "vl":"'),IFNULL(BabbleRecomended,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"GigglesListed", "vl":"',14),'{"ky":"GigglesListed", "vl":"'),IFNULL(GigglesListed,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"AvailableAmazon", "vl":"',14),'{"ky":"AvailableAmazon", "vl":"'),IFNULL(AvailableAmazon,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"AmazonURL", "vl":"',14),'{"ky":"AmazonURL", "vl":"'),IFNULL(AmazonURL,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ASIN", "vl":"',14),'{"ky":"ASIN", "vl":"'),IFNULL(ASIN,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"AmazonBestseller", "vl":"',14),'{"ky":"AmazonBestseller", "vl":"'),IFNULL(AmazonBestseller,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BabiesRUsBestseller", "vl":"',14),'{"ky":"BabiesRUsBestseller", "vl":"'),IFNULL(BabiesRUsBestseller,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BabiesRUsTopRated", "vl":"',14),'{"ky":"BabiesRUsTopRated", "vl":"'),IFNULL(BabiesRUsTopRated,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BabiesRUsRating", "vl":"',14),'{"ky":"BabiesRUsRating", "vl":"'),IFNULL(BabiesRUsRating,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"NAPPAAwardWinner", "vl":"',14),'{"ky":"NAPPAAwardWinner", "vl":"'),IFNULL(NAPPAAwardWinner,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"JPMAInnovationAwardWinner", "vl":"',14),'{"ky":"JPMAInnovationAwardWinner", "vl":"'),IFNULL(JPMAInnovationAwardWinner,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"PTPAAwardWinner", "vl":"',14),'{"ky":"PTPAAwardWinner", "vl":"'),IFNULL(PTPAAwardWinner,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"iParentingAwardWinner", "vl":"',14),'{"ky":"iParentingAwardWinner", "vl":"'),IFNULL(iParentingAwardWinner,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BrandURL", "vl":"',14),'{"ky":"BrandURL", "vl":"'),IFNULL(BrandURL,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ModelURL", "vl":"',14),'{"ky":"ModelURL", "vl":"'),IFNULL(ModelURL,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"DesignStyle", "vl":"',14),'{"ky":"DesignStyle", "vl":"'),IFNULL(DesignStyle,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BrandLevelMarketingPosition", "vl":"',14),'{"ky":"BrandLevelMarketingPosition", "vl":"'),IFNULL(BrandLevelMarketingPosition,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CollectionLevelMarketingPositon", "vl":"',14),'{"ky":"CollectionLevelMarketingPositon", "vl":"'),IFNULL(CollectionLevelMarketingPositon,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ProductOverview", "vl":"',14),'{"ky":"ProductOverview", "vl":"'),IFNULL(ProductOverview,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CountryManufacturer", "vl":"',14),'{"ky":"CountryManufacturer", "vl":"'),IFNULL(CountryManufacturer,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CRURL", "vl":"',14),'{"ky":"CRURL", "vl":"'),IFNULL(CRURL,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CRTested", "vl":"',14),'{"ky":"CRTested", "vl":"'),IFNULL(CRTested,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CROverallScore", "vl":"',14),'{"ky":"CROverallScore", "vl":"'),IFNULL(CROverallScore,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CRInterference", "vl":"',14),'{"ky":"CRInterference", "vl":"'),IFNULL(CRInterference,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CRRange", "vl":"',14),'{"ky":"CRRange", "vl":"'),IFNULL(CRRange,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CREaseOfUse", "vl":"',14),'{"ky":"CREaseOfUse", "vl":"'),IFNULL(CREaseOfUse,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CRBatteryLife", "vl":"',14),'{"ky":"CRBatteryLife", "vl":"'),IFNULL(CRBatteryLife,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CRSummary", "vl":"',14),'{"ky":"CRSummary", "vl":"'),IFNULL(CRSummary,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CRTake", "vl":"',14),'{"ky":"CRTake", "vl":"'),IFNULL(CRTake,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CRHighs", "vl":"',14),'{"ky":"CRHighs", "vl":"'),IFNULL(CRHighs,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CRLows", "vl":"',14),'{"ky":"CRLows", "vl":"'),IFNULL(CRLows,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"RecallEvent", "vl":"',14),'{"ky":"RecallEvent", "vl":"'),IFNULL(RecallEvent,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"RecallURL", "vl":"',14),'{"ky":"RecallURL", "vl":"'),IFNULL(RecallURL,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"RecallDate", "vl":"',14),'{"ky":"RecallDate", "vl":"'),IFNULL(RecallDate,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"RecallUnits", "vl":"',14),'{"ky":"RecallUnits", "vl":"'),IFNULL(RecallUnits,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"RecallHazard", "vl":"',14),'{"ky":"RecallHazard", "vl":"'),IFNULL(RecallHazard,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"RecallIncidentsInjuries", "vl":"',14),'{"ky":"RecallIncidentsInjuries", "vl":"'),IFNULL(RecallIncidentsInjuries,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"RecallSeverity", "vl":"',14),'{"ky":"RecallSeverity", "vl":"'),IFNULL(RecallSeverity,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"Encrypted", "vl":"',14),'{"ky":"Encrypted", "vl":"'),IFNULL(Encrypted,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"NightLight", "vl":"',14),'{"ky":"NightLight", "vl":"'),IFNULL(NightLight,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"NightVision", "vl":"',14),'{"ky":"NightVision", "vl":"'),IFNULL(NightVision,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"Wireless", "vl":"',14),'{"ky":"Wireless", "vl":"'),IFNULL(Wireless,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"OffSiteViewing", "vl":"',14),'{"ky":"OffSiteViewing", "vl":"'),IFNULL(OffSiteViewing,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ConnectsComputer", "vl":"',14),'{"ky":"ConnectsComputer", "vl":"'),IFNULL(ConnectsComputer,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"TwoWay", "vl":"',14),'{"ky":"TwoWay", "vl":"'),IFNULL(TwoWay,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"LCDSize", "vl":"',14),'{"ky":"LCDSize", "vl":"'),IFNULL(LCDSize,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"Video", "vl":"',14),'{"ky":"Video", "vl":"'),IFNULL(Video,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"TouchScreenMenu", "vl":"',14),'{"ky":"TouchScreenMenu", "vl":"'),IFNULL(TouchScreenMenu,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"MotionDetector", "vl":"',14),'{"ky":"MotionDetector", "vl":"'),IFNULL(MotionDetector,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"SoundActivatedSignal", "vl":"',14),'{"ky":"SoundActivatedSignal", "vl":"'),IFNULL(SoundActivatedSignal,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"OutOfRangeIndicator", "vl":"',14),'{"ky":"OutOfRangeIndicator", "vl":"'),IFNULL(OutOfRangeIndicator,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CameraFeatures", "vl":"',14),'{"ky":"CameraFeatures", "vl":"'),IFNULL(CameraFeatures,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"MonitorDocking", "vl":"',14),'{"ky":"MonitorDocking", "vl":"'),IFNULL(MonitorDocking,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"NumberAdditionalCameras", "vl":"',14),'{"ky":"NumberAdditionalCameras", "vl":"'),IFNULL(NumberAdditionalCameras,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"Frequency", "vl":"',14),'{"ky":"Frequency", "vl":"'),IFNULL(Frequency,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"SignalRange", "vl":"',14),'{"ky":"SignalRange", "vl":"'),IFNULL(SignalRange,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"PowerType", "vl":"',14),'{"ky":"PowerType", "vl":"'),IFNULL(PowerType,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"PUPowerType", "vl":"',14),'{"ky":"PUPowerType", "vl":"'),IFNULL(PUPowerType,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"RechargeableBatteryLife", "vl":"',14),'{"ky":"RechargeableBatteryLife", "vl":"'),IFNULL(RechargeableBatteryLife,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"LowBatteryIndicator", "vl":"',14),'{"ky":"LowBatteryIndicator", "vl":"'),IFNULL(LowBatteryIndicator,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"LowFeedbackMechanism", "vl":"',14),'{"ky":"LowFeedbackMechanism", "vl":"'),IFNULL(LowFeedbackMechanism,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"CustomerService", "vl":"',14),'{"ky":"CustomerService", "vl":"'),IFNULL(CustomerService,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"IncludedParentUnits", "vl":"',14),'{"ky":"IncludedParentUnits", "vl":"'),IFNULL(IncludedParentUnits,'null'),'"},',
IF(v.AdditionalParentUnitAvail IS NOT NULL,CONCAT(getProductDetailGroupsAccessories(14,'{"ky":"AdditionalParentUnitAvail", "vl":"',AdditionalParentUnitAvail),v.AdditionalParentUnitAvail,'"},'),''),
IF(v.AdditionalMonitorsAvail IS NOT NULL,CONCAT(getProductDetailGroupsAccessories(14,'{"ky":"AdditionalMonitorsAvail", "vl":"',AdditionalMonitorsAvail),v.AdditionalMonitorsAvail,'"},'),''),
IFNULL(getProductDetailGroups('{"ky":"SignalType", "vl":"',14),'{"ky":"SignalType", "vl":"'),IFNULL(SignalType,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"NetworkViewable", "vl":"',14),'{"ky":"NetworkViewable", "vl":"'),IFNULL(NetworkViewable,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"SmartPhoneViewable", "vl":"',14),'{"ky":"SmartPhoneViewable", "vl":"'),IFNULL(SmartPhoneViewable,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ImageSharing", "vl":"',14),'{"ky":"ImageSharing", "vl":"'),IFNULL(ImageSharing,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ExtraParentUnitPrice", "vl":"',14),'{"ky":"ExtraParentUnitPrice", "vl":"'),IFNULL(ExtraParentUnitPrice,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"Music", "vl":"',14),'{"ky":"Music", "vl":"'),IFNULL(Music,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"VolumeControl", "vl":"',14),'{"ky":"VolumeControl", "vl":"'),IFNULL(VolumeControl,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"Humidifier", "vl":"',14),'{"ky":"Humidifier", "vl":"'),IFNULL(Humidifier,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"TemperatureDisplay", "vl":"',14),'{"ky":"TemperatureDisplay", "vl":"'),IFNULL(TemperatureDisplay,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"Portability", "vl":"',14),'{"ky":"Portability", "vl":"'),IFNULL(Portability,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ListPrice", "vl":"',14),'{"ky":"ListPrice", "vl":"'),IFNULL(ListPrice,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"ListPriceRange", "vl":"',14),'{"ky":"ListPriceRange", "vl":"'),IFNULL(ListPriceRange,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"SalePrice", "vl":"',14),'{"ky":"SalePrice", "vl":"'),IFNULL(SalePrice,'null'),'"},',
getLowestPriceInfo(14,v.BabyMonitorID),',',
IFNULL(getProductDetailGroups('{"ky":"NewModelDiscount", "vl":"',14),'{"ky":"NewModelDiscount", "vl":"'),IFNULL(NewModelDiscount,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"DiscountedModelURL", "vl":"',14),'{"ky":"DiscountedModelURL", "vl":"'),IFNULL(DiscountedModelURL,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"FacebookURL", "vl":"',14),'{"ky":"FacebookURL", "vl":"'),IFNULL(FacebookURL,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BrandFacebookLikes", "vl":"',14),'{"ky":"BrandFacebookLikes", "vl":"'),IFNULL(BrandFacebookLikes,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"TwitterName", "vl":"',14),'{"ky":"TwitterName", "vl":"'),IFNULL(TwitterName,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"TwitterURL", "vl":"',14),'{"ky":"TwitterURL", "vl":"'),IFNULL(TwitterURL,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"BrandTwitterFollowers", "vl":"',14),'{"ky":"BrandTwitterFollowers", "vl":"'),IFNULL(BrandTwitterFollowers,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"YoutubeURL", "vl":"',14),'{"ky":"YoutubeURL", "vl":"'),IFNULL(YoutubeURL,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"YoutubeSubscribers", "vl":"',14),'{"ky":"YoutubeSubscribers", "vl":"'),IFNULL(YoutubeSubscribers,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"YoutubeViews", "vl":"',14),'{"ky":"YoutubeViews", "vl":"'),IFNULL(YoutubeViews,'null'),'"},',
IFNULL(getProductDetailGroups('{"ky":"YoutubeChannelUploadViews", "vl":"',14),'{"ky":"YoutubeChannelUploadViews", "vl":"'),IFNULL(YoutubeChannelUploadViews,'null'),'"}],',
'"mtvtrs" : {',
'"A":',IFNULL(m.A,0),',',
'"B":',IFNULL(m.B,0),',',
'"C":',IFNULL(m.C,0),',',
'"E":',IFNULL(m.E,0),',',
'"F":',IFNULL(m.F,0),',',
'"G":',IFNULL(m.G,0),',',
'"H":',IFNULL(m.H,0),',',
'"I":',IFNULL(m.I,0),',',
'"J":',IFNULL(m.J,0),',',
'"K":',IFNULL(m.K,0),',',
'"L":',IFNULL(m.L,0),'',
'}}'),'"null"','null')) AS payload   
FROM vw_babymonitor_data_ui v
JOIN vw_babymonitor_motivators m
  ON v.BabyMonitorID = m.ItemID AND
  m.CategoryID = v.CategoryID
WHERE v.BabyMonitorID = 24 AND getDefaultProductImage(14,v.BabyMonitorID) IS NOT NULL AND getLowestPriceInfo(14,v.BabyMonitorID) IS NOT NULL
