// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.ActionType;
import com.lela.data.domain.entity.ActionTypeDataOnDemand;
import com.lela.data.domain.entity.ActionTypeIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ActionTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ActionTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ActionTypeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ActionTypeIntegrationTest: @Transactional;
    
    @Autowired
    ActionTypeDataOnDemand ActionTypeIntegrationTest.dod;
    
    @Test
    public void ActionTypeIntegrationTest.testCountActionTypes() {
        Assert.assertNotNull("Data on demand for 'ActionType' failed to initialize correctly", dod.getRandomActionType());
        long count = ActionType.countActionTypes();
        Assert.assertTrue("Counter for 'ActionType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ActionTypeIntegrationTest.testFindActionType() {
        ActionType obj = dod.getRandomActionType();
        Assert.assertNotNull("Data on demand for 'ActionType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ActionType' failed to provide an identifier", id);
        obj = ActionType.findActionType(id);
        Assert.assertNotNull("Find method for 'ActionType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ActionType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ActionTypeIntegrationTest.testFindAllActionTypes() {
        Assert.assertNotNull("Data on demand for 'ActionType' failed to initialize correctly", dod.getRandomActionType());
        long count = ActionType.countActionTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'ActionType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ActionType> result = ActionType.findAllActionTypes();
        Assert.assertNotNull("Find all method for 'ActionType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ActionType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ActionTypeIntegrationTest.testFindActionTypeEntries() {
        Assert.assertNotNull("Data on demand for 'ActionType' failed to initialize correctly", dod.getRandomActionType());
        long count = ActionType.countActionTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ActionType> result = ActionType.findActionTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ActionType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ActionType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ActionTypeIntegrationTest.testFlush() {
        ActionType obj = dod.getRandomActionType();
        Assert.assertNotNull("Data on demand for 'ActionType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ActionType' failed to provide an identifier", id);
        obj = ActionType.findActionType(id);
        Assert.assertNotNull("Find method for 'ActionType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyActionType(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ActionType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ActionTypeIntegrationTest.testMergeUpdate() {
        ActionType obj = dod.getRandomActionType();
        Assert.assertNotNull("Data on demand for 'ActionType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ActionType' failed to provide an identifier", id);
        obj = ActionType.findActionType(id);
        boolean modified =  dod.modifyActionType(obj);
        Integer currentVersion = obj.getVersion();
        ActionType merged = (ActionType)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ActionType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ActionTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ActionType' failed to initialize correctly", dod.getRandomActionType());
        ActionType obj = dod.getNewTransientActionType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ActionType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ActionType' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ActionType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ActionTypeIntegrationTest.testRemove() {
        ActionType obj = dod.getRandomActionType();
        Assert.assertNotNull("Data on demand for 'ActionType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ActionType' failed to provide an identifier", id);
        obj = ActionType.findActionType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ActionType' with identifier '" + id + "'", ActionType.findActionType(id));
    }
    
}
