// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.AttributeType;
import com.lela.data.domain.entity.AttributeTypeDataOnDemand;
import com.lela.data.domain.entity.AttributeTypeIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AttributeTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AttributeTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AttributeTypeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AttributeTypeIntegrationTest: @Transactional;
    
    @Autowired
    AttributeTypeDataOnDemand AttributeTypeIntegrationTest.dod;
    
    @Test
    public void AttributeTypeIntegrationTest.testCountAttributeTypes() {
        Assert.assertNotNull("Data on demand for 'AttributeType' failed to initialize correctly", dod.getRandomAttributeType());
        long count = AttributeType.countAttributeTypes();
        Assert.assertTrue("Counter for 'AttributeType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AttributeTypeIntegrationTest.testFindAttributeType() {
        AttributeType obj = dod.getRandomAttributeType();
        Assert.assertNotNull("Data on demand for 'AttributeType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AttributeType' failed to provide an identifier", id);
        obj = AttributeType.findAttributeType(id);
        Assert.assertNotNull("Find method for 'AttributeType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'AttributeType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AttributeTypeIntegrationTest.testFindAllAttributeTypes() {
        Assert.assertNotNull("Data on demand for 'AttributeType' failed to initialize correctly", dod.getRandomAttributeType());
        long count = AttributeType.countAttributeTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'AttributeType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<AttributeType> result = AttributeType.findAllAttributeTypes();
        Assert.assertNotNull("Find all method for 'AttributeType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'AttributeType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AttributeTypeIntegrationTest.testFindAttributeTypeEntries() {
        Assert.assertNotNull("Data on demand for 'AttributeType' failed to initialize correctly", dod.getRandomAttributeType());
        long count = AttributeType.countAttributeTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<AttributeType> result = AttributeType.findAttributeTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'AttributeType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'AttributeType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AttributeTypeIntegrationTest.testFlush() {
        AttributeType obj = dod.getRandomAttributeType();
        Assert.assertNotNull("Data on demand for 'AttributeType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AttributeType' failed to provide an identifier", id);
        obj = AttributeType.findAttributeType(id);
        Assert.assertNotNull("Find method for 'AttributeType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAttributeType(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'AttributeType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AttributeTypeIntegrationTest.testMergeUpdate() {
        AttributeType obj = dod.getRandomAttributeType();
        Assert.assertNotNull("Data on demand for 'AttributeType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AttributeType' failed to provide an identifier", id);
        obj = AttributeType.findAttributeType(id);
        boolean modified =  dod.modifyAttributeType(obj);
        Integer currentVersion = obj.getVersion();
        AttributeType merged = (AttributeType)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'AttributeType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AttributeTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'AttributeType' failed to initialize correctly", dod.getRandomAttributeType());
        AttributeType obj = dod.getNewTransientAttributeType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'AttributeType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'AttributeType' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'AttributeType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AttributeTypeIntegrationTest.testRemove() {
        AttributeType obj = dod.getRandomAttributeType();
        Assert.assertNotNull("Data on demand for 'AttributeType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AttributeType' failed to provide an identifier", id);
        obj = AttributeType.findAttributeType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'AttributeType' with identifier '" + id + "'", AttributeType.findAttributeType(id));
    }
    
}
