// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.AttributeTypeHistory;
import com.lela.data.domain.entity.AttributeTypeHistoryDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect AttributeTypeHistoryDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AttributeTypeHistoryDataOnDemand: @Component;
    
    private Random AttributeTypeHistoryDataOnDemand.rnd = new SecureRandom();
    
    private List<AttributeTypeHistory> AttributeTypeHistoryDataOnDemand.data;
    
    public AttributeTypeHistory AttributeTypeHistoryDataOnDemand.getNewTransientAttributeTypeHistory(int index) {
        AttributeTypeHistory obj = new AttributeTypeHistory();
        setAttributeName(obj, index);
        setAttributeSourceNameNew(obj, index);
        setAttributeSourceNameOld(obj, index);
        setAttributeType(obj, index);
        setChangeDate(obj, index);
        setDateCreated(obj, index);
        setDateModified(obj, index);
        return obj;
    }
    
    public void AttributeTypeHistoryDataOnDemand.setAttributeName(AttributeTypeHistory obj, int index) {
        String attributeName = "attributeName_" + index;
        obj.setAttributeName(attributeName);
    }
    
    public void AttributeTypeHistoryDataOnDemand.setAttributeSourceNameNew(AttributeTypeHistory obj, int index) {
        String attributeSourceNameNew = "attributeSourceNameNew_" + index;
        obj.setAttributeSourceNameNew(attributeSourceNameNew);
    }
    
    public void AttributeTypeHistoryDataOnDemand.setAttributeSourceNameOld(AttributeTypeHistory obj, int index) {
        String attributeSourceNameOld = "attributeSourceNameOld_" + index;
        obj.setAttributeSourceNameOld(attributeSourceNameOld);
    }
    
    public void AttributeTypeHistoryDataOnDemand.setChangeDate(AttributeTypeHistory obj, int index) {
        Date changeDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setChangeDate(changeDate);
    }
    
    public void AttributeTypeHistoryDataOnDemand.setDateCreated(AttributeTypeHistory obj, int index) {
        Date dateCreated = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateCreated(dateCreated);
    }
    
    public AttributeTypeHistory AttributeTypeHistoryDataOnDemand.getSpecificAttributeTypeHistory(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        AttributeTypeHistory obj = data.get(index);
        Long id = obj.getId();
        return AttributeTypeHistory.findAttributeTypeHistory(id);
    }
    
    public AttributeTypeHistory AttributeTypeHistoryDataOnDemand.getRandomAttributeTypeHistory() {
        init();
        AttributeTypeHistory obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return AttributeTypeHistory.findAttributeTypeHistory(id);
    }
    
    public boolean AttributeTypeHistoryDataOnDemand.modifyAttributeTypeHistory(AttributeTypeHistory obj) {
        return false;
    }
    
    public void AttributeTypeHistoryDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = AttributeTypeHistory.findAttributeTypeHistoryEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'AttributeTypeHistory' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<AttributeTypeHistory>();
        for (int i = 0; i < 10; i++) {
            AttributeTypeHistory obj = getNewTransientAttributeTypeHistory(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
