// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.BrandIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect BrandIntegrationTest_Roo_Configurable {
    
    declare @type: BrandIntegrationTest: @Configurable;
    
}
