// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.CategoryAttributeRejectionFilter;
import com.lela.data.domain.entity.CategoryAttributeRejectionFilterDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect CategoryAttributeRejectionFilterDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CategoryAttributeRejectionFilterDataOnDemand: @Component;
    
    private Random CategoryAttributeRejectionFilterDataOnDemand.rnd = new SecureRandom();
    
    private List<CategoryAttributeRejectionFilter> CategoryAttributeRejectionFilterDataOnDemand.data;
    
    public CategoryAttributeRejectionFilter CategoryAttributeRejectionFilterDataOnDemand.getNewTransientCategoryAttributeRejectionFilter(int index) {
        CategoryAttributeRejectionFilter obj = new CategoryAttributeRejectionFilter();
        setAttributeType(obj, index);
        setAttributeValue(obj, index);
        setCategory(obj, index);
        setDateCreated(obj, index);
        setDateModified(obj, index);
        setRejectionReason(obj, index);
        return obj;
    }
    
    public void CategoryAttributeRejectionFilterDataOnDemand.setAttributeValue(CategoryAttributeRejectionFilter obj, int index) {
        String attributeValue = "attributeValue_" + index;
        obj.setAttributeValue(attributeValue);
    }
    
    public void CategoryAttributeRejectionFilterDataOnDemand.setDateCreated(CategoryAttributeRejectionFilter obj, int index) {
        Date dateCreated = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateCreated(dateCreated);
    }
    
    public void CategoryAttributeRejectionFilterDataOnDemand.setDateModified(CategoryAttributeRejectionFilter obj, int index) {
        Date dateModified = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateModified(dateModified);
    }
    
    public CategoryAttributeRejectionFilter CategoryAttributeRejectionFilterDataOnDemand.getSpecificCategoryAttributeRejectionFilter(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        CategoryAttributeRejectionFilter obj = data.get(index);
        Long id = obj.getId();
        return CategoryAttributeRejectionFilter.findCategoryAttributeRejectionFilter(id);
    }
    
    public CategoryAttributeRejectionFilter CategoryAttributeRejectionFilterDataOnDemand.getRandomCategoryAttributeRejectionFilter() {
        init();
        CategoryAttributeRejectionFilter obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return CategoryAttributeRejectionFilter.findCategoryAttributeRejectionFilter(id);
    }
    
    public boolean CategoryAttributeRejectionFilterDataOnDemand.modifyCategoryAttributeRejectionFilter(CategoryAttributeRejectionFilter obj) {
        return false;
    }
    
    public void CategoryAttributeRejectionFilterDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = CategoryAttributeRejectionFilter.findCategoryAttributeRejectionFilterEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'CategoryAttributeRejectionFilter' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<CategoryAttributeRejectionFilter>();
        for (int i = 0; i < 10; i++) {
            CategoryAttributeRejectionFilter obj = getNewTransientCategoryAttributeRejectionFilter(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
