// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.Category;
import com.lela.data.domain.entity.CategoryDataOnDemand;
import com.lela.data.domain.entity.CategorySubdepartment;
import com.lela.data.domain.entity.CategorySubdepartmentDataOnDemand;
import com.lela.data.domain.entity.Subdepartment;
import com.lela.data.domain.entity.SubdepartmentDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect CategorySubdepartmentDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CategorySubdepartmentDataOnDemand: @Component;
    
    private Random CategorySubdepartmentDataOnDemand.rnd = new SecureRandom();
    
    private List<CategorySubdepartment> CategorySubdepartmentDataOnDemand.data;
    
    @Autowired
    CategoryDataOnDemand CategorySubdepartmentDataOnDemand.categoryDataOnDemand;
    
    @Autowired
    SubdepartmentDataOnDemand CategorySubdepartmentDataOnDemand.subdepartmentDataOnDemand;
    
    public CategorySubdepartment CategorySubdepartmentDataOnDemand.getNewTransientCategorySubdepartment(int index) {
        CategorySubdepartment obj = new CategorySubdepartment();
        setCategory(obj, index);
        setCategoryOrder(obj, index);
        setDateCreated(obj, index);
        setDateModified(obj, index);
        setSubdepartment(obj, index);
        return obj;
    }
    
    public void CategorySubdepartmentDataOnDemand.setCategory(CategorySubdepartment obj, int index) {
        Category category = categoryDataOnDemand.getRandomCategory();
        obj.setCategory(category);
    }
    
    public void CategorySubdepartmentDataOnDemand.setCategoryOrder(CategorySubdepartment obj, int index) {
        Integer categoryOrder = new Integer(index);
        obj.setCategoryOrder(categoryOrder);
    }
    
    public void CategorySubdepartmentDataOnDemand.setDateCreated(CategorySubdepartment obj, int index) {
        Date dateCreated = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateCreated(dateCreated);
    }
    
    public void CategorySubdepartmentDataOnDemand.setDateModified(CategorySubdepartment obj, int index) {
        Date dateModified = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateModified(dateModified);
    }
    
    public void CategorySubdepartmentDataOnDemand.setSubdepartment(CategorySubdepartment obj, int index) {
        Subdepartment subdepartment = subdepartmentDataOnDemand.getRandomSubdepartment();
        obj.setSubdepartment(subdepartment);
    }
    
    public CategorySubdepartment CategorySubdepartmentDataOnDemand.getSpecificCategorySubdepartment(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        CategorySubdepartment obj = data.get(index);
        Long id = obj.getId();
        return CategorySubdepartment.findCategorySubdepartment(id);
    }
    
    public CategorySubdepartment CategorySubdepartmentDataOnDemand.getRandomCategorySubdepartment() {
        init();
        CategorySubdepartment obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return CategorySubdepartment.findCategorySubdepartment(id);
    }
    
    public boolean CategorySubdepartmentDataOnDemand.modifyCategorySubdepartment(CategorySubdepartment obj) {
        return false;
    }
    
    public void CategorySubdepartmentDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = CategorySubdepartment.findCategorySubdepartmentEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'CategorySubdepartment' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<CategorySubdepartment>();
        for (int i = 0; i < 10; i++) {
            CategorySubdepartment obj = getNewTransientCategorySubdepartment(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
