// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.ConditionType;
import com.lela.data.domain.entity.ConditionTypeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ConditionTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ConditionTypeDataOnDemand: @Component;
    
    private Random ConditionTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<ConditionType> ConditionTypeDataOnDemand.data;
    
    public ConditionType ConditionTypeDataOnDemand.getNewTransientConditionType(int index) {
        ConditionType obj = new ConditionType();
        setConditionTypeName(obj, index);
        setDateCreated(obj, index);
        setDateModified(obj, index);
        setUseInLela(obj, index);
        return obj;
    }
    
    public void ConditionTypeDataOnDemand.setConditionTypeName(ConditionType obj, int index) {
        String conditionTypeName = "conditionTypeName_" + index;
        obj.setConditionTypeName(conditionTypeName);
    }
    
    public void ConditionTypeDataOnDemand.setDateCreated(ConditionType obj, int index) {
        Date dateCreated = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateCreated(dateCreated);
    }
    
    public void ConditionTypeDataOnDemand.setDateModified(ConditionType obj, int index) {
        Date dateModified = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateModified(dateModified);
    }
    
    public void ConditionTypeDataOnDemand.setUseInLela(ConditionType obj, int index) {
        Boolean useInLela = Boolean.TRUE;
        obj.setUseInLela(useInLela);
    }
    
    public ConditionType ConditionTypeDataOnDemand.getSpecificConditionType(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ConditionType obj = data.get(index);
        Long id = obj.getId();
        return ConditionType.findConditionType(id);
    }
    
    public ConditionType ConditionTypeDataOnDemand.getRandomConditionType() {
        init();
        ConditionType obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ConditionType.findConditionType(id);
    }
    
    public boolean ConditionTypeDataOnDemand.modifyConditionType(ConditionType obj) {
        return false;
    }
    
    public void ConditionTypeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ConditionType.findConditionTypeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ConditionType' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ConditionType>();
        for (int i = 0; i < 10; i++) {
            ConditionType obj = getNewTransientConditionType(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
