// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.DesignStyleMotivator;
import com.lela.data.domain.entity.DesignStyleMotivatorDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect DesignStyleMotivatorDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DesignStyleMotivatorDataOnDemand: @Component;
    
    private Random DesignStyleMotivatorDataOnDemand.rnd = new SecureRandom();
    
    private List<DesignStyleMotivator> DesignStyleMotivatorDataOnDemand.data;
    
    public DesignStyleMotivator DesignStyleMotivatorDataOnDemand.getNewTransientDesignStyleMotivator(int index) {
        DesignStyleMotivator obj = new DesignStyleMotivator();
        setCategory(obj, index);
        setDateCreated(obj, index);
        setDateModified(obj, index);
        setDesignStyle(obj, index);
        setH(obj, index);
        setI(obj, index);
        setJ(obj, index);
        setK(obj, index);
        setL(obj, index);
        return obj;
    }
    
    public void DesignStyleMotivatorDataOnDemand.setDateCreated(DesignStyleMotivator obj, int index) {
        Date dateCreated = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateCreated(dateCreated);
    }
    
    public void DesignStyleMotivatorDataOnDemand.setDateModified(DesignStyleMotivator obj, int index) {
        Date dateModified = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateModified(dateModified);
    }
    
    public void DesignStyleMotivatorDataOnDemand.setDesignStyle(DesignStyleMotivator obj, int index) {
        String designStyle = "designStyle_" + index;
        obj.setDesignStyle(designStyle);
    }
    
    public void DesignStyleMotivatorDataOnDemand.setH(DesignStyleMotivator obj, int index) {
        Integer h = new Integer(index);
        obj.setH(h);
    }
    
    public void DesignStyleMotivatorDataOnDemand.setI(DesignStyleMotivator obj, int index) {
        Integer i = new Integer(index);
        obj.setI(i);
    }
    
    public void DesignStyleMotivatorDataOnDemand.setJ(DesignStyleMotivator obj, int index) {
        Integer j = new Integer(index);
        obj.setJ(j);
    }
    
    public void DesignStyleMotivatorDataOnDemand.setK(DesignStyleMotivator obj, int index) {
        Integer k = new Integer(index);
        obj.setK(k);
    }
    
    public void DesignStyleMotivatorDataOnDemand.setL(DesignStyleMotivator obj, int index) {
        Integer l = new Integer(index);
        obj.setL(l);
    }
    
    public DesignStyleMotivator DesignStyleMotivatorDataOnDemand.getSpecificDesignStyleMotivator(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        DesignStyleMotivator obj = data.get(index);
        Long id = obj.getId();
        return DesignStyleMotivator.findDesignStyleMotivator(id);
    }
    
    public DesignStyleMotivator DesignStyleMotivatorDataOnDemand.getRandomDesignStyleMotivator() {
        init();
        DesignStyleMotivator obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return DesignStyleMotivator.findDesignStyleMotivator(id);
    }
    
    public boolean DesignStyleMotivatorDataOnDemand.modifyDesignStyleMotivator(DesignStyleMotivator obj) {
        return false;
    }
    
    public void DesignStyleMotivatorDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = DesignStyleMotivator.findDesignStyleMotivatorEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'DesignStyleMotivator' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<DesignStyleMotivator>();
        for (int i = 0; i < 10; i++) {
            DesignStyleMotivator obj = getNewTransientDesignStyleMotivator(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
