// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.DesignStyleMotivator;
import com.lela.data.domain.entity.DesignStyleMotivatorDataOnDemand;
import com.lela.data.domain.entity.DesignStyleMotivatorIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DesignStyleMotivatorIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DesignStyleMotivatorIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DesignStyleMotivatorIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DesignStyleMotivatorIntegrationTest: @Transactional;
    
    @Autowired
    DesignStyleMotivatorDataOnDemand DesignStyleMotivatorIntegrationTest.dod;
    
    @Test
    public void DesignStyleMotivatorIntegrationTest.testCountDesignStyleMotivators() {
        Assert.assertNotNull("Data on demand for 'DesignStyleMotivator' failed to initialize correctly", dod.getRandomDesignStyleMotivator());
        long count = DesignStyleMotivator.countDesignStyleMotivators();
        Assert.assertTrue("Counter for 'DesignStyleMotivator' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DesignStyleMotivatorIntegrationTest.testFindDesignStyleMotivator() {
        DesignStyleMotivator obj = dod.getRandomDesignStyleMotivator();
        Assert.assertNotNull("Data on demand for 'DesignStyleMotivator' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DesignStyleMotivator' failed to provide an identifier", id);
        obj = DesignStyleMotivator.findDesignStyleMotivator(id);
        Assert.assertNotNull("Find method for 'DesignStyleMotivator' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'DesignStyleMotivator' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DesignStyleMotivatorIntegrationTest.testFindAllDesignStyleMotivators() {
        Assert.assertNotNull("Data on demand for 'DesignStyleMotivator' failed to initialize correctly", dod.getRandomDesignStyleMotivator());
        long count = DesignStyleMotivator.countDesignStyleMotivators();
        Assert.assertTrue("Too expensive to perform a find all test for 'DesignStyleMotivator', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<DesignStyleMotivator> result = DesignStyleMotivator.findAllDesignStyleMotivators();
        Assert.assertNotNull("Find all method for 'DesignStyleMotivator' illegally returned null", result);
        Assert.assertTrue("Find all method for 'DesignStyleMotivator' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DesignStyleMotivatorIntegrationTest.testFindDesignStyleMotivatorEntries() {
        Assert.assertNotNull("Data on demand for 'DesignStyleMotivator' failed to initialize correctly", dod.getRandomDesignStyleMotivator());
        long count = DesignStyleMotivator.countDesignStyleMotivators();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<DesignStyleMotivator> result = DesignStyleMotivator.findDesignStyleMotivatorEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'DesignStyleMotivator' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'DesignStyleMotivator' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DesignStyleMotivatorIntegrationTest.testFlush() {
        DesignStyleMotivator obj = dod.getRandomDesignStyleMotivator();
        Assert.assertNotNull("Data on demand for 'DesignStyleMotivator' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DesignStyleMotivator' failed to provide an identifier", id);
        obj = DesignStyleMotivator.findDesignStyleMotivator(id);
        Assert.assertNotNull("Find method for 'DesignStyleMotivator' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDesignStyleMotivator(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'DesignStyleMotivator' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DesignStyleMotivatorIntegrationTest.testMergeUpdate() {
        DesignStyleMotivator obj = dod.getRandomDesignStyleMotivator();
        Assert.assertNotNull("Data on demand for 'DesignStyleMotivator' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DesignStyleMotivator' failed to provide an identifier", id);
        obj = DesignStyleMotivator.findDesignStyleMotivator(id);
        boolean modified =  dod.modifyDesignStyleMotivator(obj);
        Integer currentVersion = obj.getVersion();
        DesignStyleMotivator merged = (DesignStyleMotivator)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'DesignStyleMotivator' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DesignStyleMotivatorIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'DesignStyleMotivator' failed to initialize correctly", dod.getRandomDesignStyleMotivator());
        DesignStyleMotivator obj = dod.getNewTransientDesignStyleMotivator(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'DesignStyleMotivator' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'DesignStyleMotivator' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'DesignStyleMotivator' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DesignStyleMotivatorIntegrationTest.testRemove() {
        DesignStyleMotivator obj = dod.getRandomDesignStyleMotivator();
        Assert.assertNotNull("Data on demand for 'DesignStyleMotivator' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DesignStyleMotivator' failed to provide an identifier", id);
        obj = DesignStyleMotivator.findDesignStyleMotivator(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'DesignStyleMotivator' with identifier '" + id + "'", DesignStyleMotivator.findDesignStyleMotivator(id));
    }
    
}
