// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.FunctionalFilterCategory;
import com.lela.data.domain.entity.FunctionalFilterCategoryDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect FunctionalFilterCategoryDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FunctionalFilterCategoryDataOnDemand: @Component;
    
    private Random FunctionalFilterCategoryDataOnDemand.rnd = new SecureRandom();
    
    private List<FunctionalFilterCategory> FunctionalFilterCategoryDataOnDemand.data;
    
    public FunctionalFilterCategory FunctionalFilterCategoryDataOnDemand.getNewTransientFunctionalFilterCategory(int index) {
        FunctionalFilterCategory obj = new FunctionalFilterCategory();
        setCategory(obj, index);
        setDateCreated(obj, index);
        setDateModified(obj, index);
        setFunctionalFilter(obj, index);
        setObjectId(obj, index);
        return obj;
    }
    
    public void FunctionalFilterCategoryDataOnDemand.setDateCreated(FunctionalFilterCategory obj, int index) {
        Date dateCreated = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateCreated(dateCreated);
    }
    
    public void FunctionalFilterCategoryDataOnDemand.setDateModified(FunctionalFilterCategory obj, int index) {
        Date dateModified = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateModified(dateModified);
    }
    
    public void FunctionalFilterCategoryDataOnDemand.setObjectId(FunctionalFilterCategory obj, int index) {
        String objectId = "objectId_" + index;
        obj.setObjectId(objectId);
    }
    
    public FunctionalFilterCategory FunctionalFilterCategoryDataOnDemand.getSpecificFunctionalFilterCategory(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        FunctionalFilterCategory obj = data.get(index);
        Long id = obj.getId();
        return FunctionalFilterCategory.findFunctionalFilterCategory(id);
    }
    
    public FunctionalFilterCategory FunctionalFilterCategoryDataOnDemand.getRandomFunctionalFilterCategory() {
        init();
        FunctionalFilterCategory obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return FunctionalFilterCategory.findFunctionalFilterCategory(id);
    }
    
    public boolean FunctionalFilterCategoryDataOnDemand.modifyFunctionalFilterCategory(FunctionalFilterCategory obj) {
        return false;
    }
    
    public void FunctionalFilterCategoryDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = FunctionalFilterCategory.findFunctionalFilterCategoryEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'FunctionalFilterCategory' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<FunctionalFilterCategory>();
        for (int i = 0; i < 10; i++) {
            FunctionalFilterCategory obj = getNewTransientFunctionalFilterCategory(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
