// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.FunctionalFilterDepartment;
import com.lela.data.domain.entity.FunctionalFilterDepartmentDataOnDemand;
import com.lela.data.domain.entity.FunctionalFilterDepartmentIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FunctionalFilterDepartmentIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FunctionalFilterDepartmentIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FunctionalFilterDepartmentIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: FunctionalFilterDepartmentIntegrationTest: @Transactional;
    
    @Autowired
    FunctionalFilterDepartmentDataOnDemand FunctionalFilterDepartmentIntegrationTest.dod;
    
    @Test
    public void FunctionalFilterDepartmentIntegrationTest.testCountFunctionalFilterDepartments() {
        Assert.assertNotNull("Data on demand for 'FunctionalFilterDepartment' failed to initialize correctly", dod.getRandomFunctionalFilterDepartment());
        long count = FunctionalFilterDepartment.countFunctionalFilterDepartments();
        Assert.assertTrue("Counter for 'FunctionalFilterDepartment' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FunctionalFilterDepartmentIntegrationTest.testFindFunctionalFilterDepartment() {
        FunctionalFilterDepartment obj = dod.getRandomFunctionalFilterDepartment();
        Assert.assertNotNull("Data on demand for 'FunctionalFilterDepartment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FunctionalFilterDepartment' failed to provide an identifier", id);
        obj = FunctionalFilterDepartment.findFunctionalFilterDepartment(id);
        Assert.assertNotNull("Find method for 'FunctionalFilterDepartment' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'FunctionalFilterDepartment' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FunctionalFilterDepartmentIntegrationTest.testFindAllFunctionalFilterDepartments() {
        Assert.assertNotNull("Data on demand for 'FunctionalFilterDepartment' failed to initialize correctly", dod.getRandomFunctionalFilterDepartment());
        long count = FunctionalFilterDepartment.countFunctionalFilterDepartments();
        Assert.assertTrue("Too expensive to perform a find all test for 'FunctionalFilterDepartment', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<FunctionalFilterDepartment> result = FunctionalFilterDepartment.findAllFunctionalFilterDepartments();
        Assert.assertNotNull("Find all method for 'FunctionalFilterDepartment' illegally returned null", result);
        Assert.assertTrue("Find all method for 'FunctionalFilterDepartment' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FunctionalFilterDepartmentIntegrationTest.testFindFunctionalFilterDepartmentEntries() {
        Assert.assertNotNull("Data on demand for 'FunctionalFilterDepartment' failed to initialize correctly", dod.getRandomFunctionalFilterDepartment());
        long count = FunctionalFilterDepartment.countFunctionalFilterDepartments();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<FunctionalFilterDepartment> result = FunctionalFilterDepartment.findFunctionalFilterDepartmentEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'FunctionalFilterDepartment' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'FunctionalFilterDepartment' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FunctionalFilterDepartmentIntegrationTest.testFlush() {
        FunctionalFilterDepartment obj = dod.getRandomFunctionalFilterDepartment();
        Assert.assertNotNull("Data on demand for 'FunctionalFilterDepartment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FunctionalFilterDepartment' failed to provide an identifier", id);
        obj = FunctionalFilterDepartment.findFunctionalFilterDepartment(id);
        Assert.assertNotNull("Find method for 'FunctionalFilterDepartment' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFunctionalFilterDepartment(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'FunctionalFilterDepartment' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FunctionalFilterDepartmentIntegrationTest.testMergeUpdate() {
        FunctionalFilterDepartment obj = dod.getRandomFunctionalFilterDepartment();
        Assert.assertNotNull("Data on demand for 'FunctionalFilterDepartment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FunctionalFilterDepartment' failed to provide an identifier", id);
        obj = FunctionalFilterDepartment.findFunctionalFilterDepartment(id);
        boolean modified =  dod.modifyFunctionalFilterDepartment(obj);
        Integer currentVersion = obj.getVersion();
        FunctionalFilterDepartment merged = (FunctionalFilterDepartment)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'FunctionalFilterDepartment' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FunctionalFilterDepartmentIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'FunctionalFilterDepartment' failed to initialize correctly", dod.getRandomFunctionalFilterDepartment());
        FunctionalFilterDepartment obj = dod.getNewTransientFunctionalFilterDepartment(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'FunctionalFilterDepartment' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'FunctionalFilterDepartment' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'FunctionalFilterDepartment' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FunctionalFilterDepartmentIntegrationTest.testRemove() {
        FunctionalFilterDepartment obj = dod.getRandomFunctionalFilterDepartment();
        Assert.assertNotNull("Data on demand for 'FunctionalFilterDepartment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FunctionalFilterDepartment' failed to provide an identifier", id);
        obj = FunctionalFilterDepartment.findFunctionalFilterDepartment(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'FunctionalFilterDepartment' with identifier '" + id + "'", FunctionalFilterDepartment.findFunctionalFilterDepartment(id));
    }
    
}
