// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.IdentifierType;
import com.lela.data.domain.entity.IdentifierTypeDataOnDemand;
import com.lela.data.domain.entity.IdentifierTypeIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect IdentifierTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: IdentifierTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: IdentifierTypeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: IdentifierTypeIntegrationTest: @Transactional;
    
    @Autowired
    IdentifierTypeDataOnDemand IdentifierTypeIntegrationTest.dod;
    
    @Test
    public void IdentifierTypeIntegrationTest.testCountIdentifierTypes() {
        Assert.assertNotNull("Data on demand for 'IdentifierType' failed to initialize correctly", dod.getRandomIdentifierType());
        long count = IdentifierType.countIdentifierTypes();
        Assert.assertTrue("Counter for 'IdentifierType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void IdentifierTypeIntegrationTest.testFindIdentifierType() {
        IdentifierType obj = dod.getRandomIdentifierType();
        Assert.assertNotNull("Data on demand for 'IdentifierType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'IdentifierType' failed to provide an identifier", id);
        obj = IdentifierType.findIdentifierType(id);
        Assert.assertNotNull("Find method for 'IdentifierType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'IdentifierType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void IdentifierTypeIntegrationTest.testFindAllIdentifierTypes() {
        Assert.assertNotNull("Data on demand for 'IdentifierType' failed to initialize correctly", dod.getRandomIdentifierType());
        long count = IdentifierType.countIdentifierTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'IdentifierType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<IdentifierType> result = IdentifierType.findAllIdentifierTypes();
        Assert.assertNotNull("Find all method for 'IdentifierType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'IdentifierType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void IdentifierTypeIntegrationTest.testFindIdentifierTypeEntries() {
        Assert.assertNotNull("Data on demand for 'IdentifierType' failed to initialize correctly", dod.getRandomIdentifierType());
        long count = IdentifierType.countIdentifierTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<IdentifierType> result = IdentifierType.findIdentifierTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'IdentifierType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'IdentifierType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void IdentifierTypeIntegrationTest.testFlush() {
        IdentifierType obj = dod.getRandomIdentifierType();
        Assert.assertNotNull("Data on demand for 'IdentifierType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'IdentifierType' failed to provide an identifier", id);
        obj = IdentifierType.findIdentifierType(id);
        Assert.assertNotNull("Find method for 'IdentifierType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyIdentifierType(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'IdentifierType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void IdentifierTypeIntegrationTest.testMergeUpdate() {
        IdentifierType obj = dod.getRandomIdentifierType();
        Assert.assertNotNull("Data on demand for 'IdentifierType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'IdentifierType' failed to provide an identifier", id);
        obj = IdentifierType.findIdentifierType(id);
        boolean modified =  dod.modifyIdentifierType(obj);
        Integer currentVersion = obj.getVersion();
        IdentifierType merged = (IdentifierType)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'IdentifierType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void IdentifierTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'IdentifierType' failed to initialize correctly", dod.getRandomIdentifierType());
        IdentifierType obj = dod.getNewTransientIdentifierType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'IdentifierType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'IdentifierType' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'IdentifierType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void IdentifierTypeIntegrationTest.testRemove() {
        IdentifierType obj = dod.getRandomIdentifierType();
        Assert.assertNotNull("Data on demand for 'IdentifierType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'IdentifierType' failed to provide an identifier", id);
        obj = IdentifierType.findIdentifierType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'IdentifierType' with identifier '" + id + "'", IdentifierType.findIdentifierType(id));
    }
    
}
