// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.InputValidationList;
import com.lela.data.domain.entity.InputValidationListDataOnDemand;
import com.lela.data.domain.entity.InputValidationListIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect InputValidationListIntegrationTest_Roo_IntegrationTest {
    
    declare @type: InputValidationListIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: InputValidationListIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: InputValidationListIntegrationTest: @Transactional;
    
    @Autowired
    InputValidationListDataOnDemand InputValidationListIntegrationTest.dod;
    
    @Test
    public void InputValidationListIntegrationTest.testCountInputValidationLists() {
        Assert.assertNotNull("Data on demand for 'InputValidationList' failed to initialize correctly", dod.getRandomInputValidationList());
        long count = InputValidationList.countInputValidationLists();
        Assert.assertTrue("Counter for 'InputValidationList' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void InputValidationListIntegrationTest.testFindInputValidationList() {
        InputValidationList obj = dod.getRandomInputValidationList();
        Assert.assertNotNull("Data on demand for 'InputValidationList' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'InputValidationList' failed to provide an identifier", id);
        obj = InputValidationList.findInputValidationList(id);
        Assert.assertNotNull("Find method for 'InputValidationList' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'InputValidationList' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void InputValidationListIntegrationTest.testFindAllInputValidationLists() {
        Assert.assertNotNull("Data on demand for 'InputValidationList' failed to initialize correctly", dod.getRandomInputValidationList());
        long count = InputValidationList.countInputValidationLists();
        Assert.assertTrue("Too expensive to perform a find all test for 'InputValidationList', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<InputValidationList> result = InputValidationList.findAllInputValidationLists();
        Assert.assertNotNull("Find all method for 'InputValidationList' illegally returned null", result);
        Assert.assertTrue("Find all method for 'InputValidationList' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void InputValidationListIntegrationTest.testFindInputValidationListEntries() {
        Assert.assertNotNull("Data on demand for 'InputValidationList' failed to initialize correctly", dod.getRandomInputValidationList());
        long count = InputValidationList.countInputValidationLists();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<InputValidationList> result = InputValidationList.findInputValidationListEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'InputValidationList' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'InputValidationList' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void InputValidationListIntegrationTest.testFlush() {
        InputValidationList obj = dod.getRandomInputValidationList();
        Assert.assertNotNull("Data on demand for 'InputValidationList' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'InputValidationList' failed to provide an identifier", id);
        obj = InputValidationList.findInputValidationList(id);
        Assert.assertNotNull("Find method for 'InputValidationList' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyInputValidationList(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'InputValidationList' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void InputValidationListIntegrationTest.testMergeUpdate() {
        InputValidationList obj = dod.getRandomInputValidationList();
        Assert.assertNotNull("Data on demand for 'InputValidationList' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'InputValidationList' failed to provide an identifier", id);
        obj = InputValidationList.findInputValidationList(id);
        boolean modified =  dod.modifyInputValidationList(obj);
        Integer currentVersion = obj.getVersion();
        InputValidationList merged = (InputValidationList)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'InputValidationList' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void InputValidationListIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'InputValidationList' failed to initialize correctly", dod.getRandomInputValidationList());
        InputValidationList obj = dod.getNewTransientInputValidationList(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'InputValidationList' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'InputValidationList' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'InputValidationList' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void InputValidationListIntegrationTest.testRemove() {
        InputValidationList obj = dod.getRandomInputValidationList();
        Assert.assertNotNull("Data on demand for 'InputValidationList' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'InputValidationList' failed to provide an identifier", id);
        obj = InputValidationList.findInputValidationList(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'InputValidationList' with identifier '" + id + "'", InputValidationList.findInputValidationList(id));
    }
    
}
