// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.ItemStatus;
import com.lela.data.domain.entity.ItemStatusDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ItemStatusDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ItemStatusDataOnDemand: @Component;
    
    private Random ItemStatusDataOnDemand.rnd = new SecureRandom();
    
    private List<ItemStatus> ItemStatusDataOnDemand.data;
    
    public ItemStatus ItemStatusDataOnDemand.getNewTransientItemStatus(int index) {
        ItemStatus obj = new ItemStatus();
        setDateCreated(obj, index);
        setDateModified(obj, index);
        setItemStatusName(obj, index);
        return obj;
    }
    
    public void ItemStatusDataOnDemand.setDateCreated(ItemStatus obj, int index) {
        Date dateCreated = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateCreated(dateCreated);
    }
    
    public void ItemStatusDataOnDemand.setDateModified(ItemStatus obj, int index) {
        Date dateModified = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateModified(dateModified);
    }
    
    public void ItemStatusDataOnDemand.setItemStatusName(ItemStatus obj, int index) {
        String itemStatusName = "itemStatusName_" + index;
        obj.setItemStatusName(itemStatusName);
    }
    
    public ItemStatus ItemStatusDataOnDemand.getSpecificItemStatus(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ItemStatus obj = data.get(index);
        Long id = obj.getId();
        return ItemStatus.findItemStatus(id);
    }
    
    public ItemStatus ItemStatusDataOnDemand.getRandomItemStatus() {
        init();
        ItemStatus obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ItemStatus.findItemStatus(id);
    }
    
    public boolean ItemStatusDataOnDemand.modifyItemStatus(ItemStatus obj) {
        return false;
    }
    
    public void ItemStatusDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ItemStatus.findItemStatusEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ItemStatus' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ItemStatus>();
        for (int i = 0; i < 10; i++) {
            ItemStatus obj = getNewTransientItemStatus(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
