// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.ItemColorMerchant;
import com.lela.data.domain.entity.ItemColorMerchantDataOnDemand;
import com.lela.data.domain.entity.MerchantDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ItemColorMerchantDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ItemColorMerchantDataOnDemand: @Component;
    
    private Random ItemColorMerchantDataOnDemand.rnd = new SecureRandom();
    
    private List<ItemColorMerchant> ItemColorMerchantDataOnDemand.data;
    
    @Autowired
    MerchantDataOnDemand ItemColorMerchantDataOnDemand.merchantDataOnDemand;
    
    public void ItemColorMerchantDataOnDemand.setAvailable(ItemColorMerchant obj, int index) {
        Boolean available = Boolean.TRUE;
        obj.setAvailable(available);
    }
    
    public void ItemColorMerchantDataOnDemand.setDateCreated(ItemColorMerchant obj, int index) {
        Date dateCreated = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateCreated(dateCreated);
    }
    
    public void ItemColorMerchantDataOnDemand.setDateModified(ItemColorMerchant obj, int index) {
        Date dateModified = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateModified(dateModified);
    }
    
    public ItemColorMerchant ItemColorMerchantDataOnDemand.getSpecificItemColorMerchant(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ItemColorMerchant obj = data.get(index);
        Long id = obj.getId();
        return ItemColorMerchant.findItemColorMerchant(id);
    }
    
    public ItemColorMerchant ItemColorMerchantDataOnDemand.getRandomItemColorMerchant() {
        init();
        ItemColorMerchant obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ItemColorMerchant.findItemColorMerchant(id);
    }
    
    public boolean ItemColorMerchantDataOnDemand.modifyItemColorMerchant(ItemColorMerchant obj) {
        return false;
    }
    
    public void ItemColorMerchantDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ItemColorMerchant.findItemColorMerchantEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ItemColorMerchant' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ItemColorMerchant>();
        for (int i = 0; i < 10; i++) {
            ItemColorMerchant obj = getNewTransientItemColorMerchant(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
