// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.Locale;
import com.lela.data.domain.entity.LocaleDataOnDemand;
import com.lela.data.domain.entity.LocaleIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect LocaleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: LocaleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: LocaleIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: LocaleIntegrationTest: @Transactional;
    
    @Autowired
    LocaleDataOnDemand LocaleIntegrationTest.dod;
    
    @Test
    public void LocaleIntegrationTest.testCountLocales() {
        Assert.assertNotNull("Data on demand for 'Locale' failed to initialize correctly", dod.getRandomLocale());
        long count = Locale.countLocales();
        Assert.assertTrue("Counter for 'Locale' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void LocaleIntegrationTest.testFindLocale() {
        Locale obj = dod.getRandomLocale();
        Assert.assertNotNull("Data on demand for 'Locale' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Locale' failed to provide an identifier", id);
        obj = Locale.findLocale(id);
        Assert.assertNotNull("Find method for 'Locale' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Locale' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void LocaleIntegrationTest.testFindAllLocales() {
        Assert.assertNotNull("Data on demand for 'Locale' failed to initialize correctly", dod.getRandomLocale());
        long count = Locale.countLocales();
        Assert.assertTrue("Too expensive to perform a find all test for 'Locale', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Locale> result = Locale.findAllLocales();
        Assert.assertNotNull("Find all method for 'Locale' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Locale' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void LocaleIntegrationTest.testFindLocaleEntries() {
        Assert.assertNotNull("Data on demand for 'Locale' failed to initialize correctly", dod.getRandomLocale());
        long count = Locale.countLocales();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Locale> result = Locale.findLocaleEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Locale' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Locale' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void LocaleIntegrationTest.testFlush() {
        Locale obj = dod.getRandomLocale();
        Assert.assertNotNull("Data on demand for 'Locale' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Locale' failed to provide an identifier", id);
        obj = Locale.findLocale(id);
        Assert.assertNotNull("Find method for 'Locale' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyLocale(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Locale' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LocaleIntegrationTest.testMergeUpdate() {
        Locale obj = dod.getRandomLocale();
        Assert.assertNotNull("Data on demand for 'Locale' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Locale' failed to provide an identifier", id);
        obj = Locale.findLocale(id);
        boolean modified =  dod.modifyLocale(obj);
        Integer currentVersion = obj.getVersion();
        Locale merged = (Locale)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Locale' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LocaleIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Locale' failed to initialize correctly", dod.getRandomLocale());
        Locale obj = dod.getNewTransientLocale(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Locale' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Locale' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Locale' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void LocaleIntegrationTest.testRemove() {
        Locale obj = dod.getRandomLocale();
        Assert.assertNotNull("Data on demand for 'Locale' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Locale' failed to provide an identifier", id);
        obj = Locale.findLocale(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Locale' with identifier '" + id + "'", Locale.findLocale(id));
    }
    
}
