// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.Manufacturer;
import com.lela.data.domain.entity.ManufacturerDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ManufacturerDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ManufacturerDataOnDemand: @Component;
    
    private Random ManufacturerDataOnDemand.rnd = new SecureRandom();
    
    private List<Manufacturer> ManufacturerDataOnDemand.data;
    
    public Manufacturer ManufacturerDataOnDemand.getNewTransientManufacturer(int index) {
        Manufacturer obj = new Manufacturer();
        setDateCreated(obj, index);
        setDateModified(obj, index);
        setManufacturerName(obj, index);
        return obj;
    }
    
    public void ManufacturerDataOnDemand.setDateCreated(Manufacturer obj, int index) {
        Date dateCreated = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateCreated(dateCreated);
    }
    
    public void ManufacturerDataOnDemand.setDateModified(Manufacturer obj, int index) {
        Date dateModified = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateModified(dateModified);
    }
    
    public void ManufacturerDataOnDemand.setManufacturerName(Manufacturer obj, int index) {
        String manufacturerName = "manufacturerName_" + index;
        obj.setManufacturerName(manufacturerName);
    }
    
    public Manufacturer ManufacturerDataOnDemand.getSpecificManufacturer(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Manufacturer obj = data.get(index);
        Long id = obj.getId();
        return Manufacturer.findManufacturer(id);
    }
    
    public Manufacturer ManufacturerDataOnDemand.getRandomManufacturer() {
        init();
        Manufacturer obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Manufacturer.findManufacturer(id);
    }
    
    public boolean ManufacturerDataOnDemand.modifyManufacturer(Manufacturer obj) {
        return false;
    }
    
    public void ManufacturerDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Manufacturer.findManufacturerEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Manufacturer' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Manufacturer>();
        for (int i = 0; i < 10; i++) {
            Manufacturer obj = getNewTransientManufacturer(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
