// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.Manufacturer;
import com.lela.data.domain.entity.ManufacturerDataOnDemand;
import com.lela.data.domain.entity.ManufacturerIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ManufacturerIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ManufacturerIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ManufacturerIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ManufacturerIntegrationTest: @Transactional;
    
    @Autowired
    ManufacturerDataOnDemand ManufacturerIntegrationTest.dod;
    
    @Test
    public void ManufacturerIntegrationTest.testCountManufacturers() {
        Assert.assertNotNull("Data on demand for 'Manufacturer' failed to initialize correctly", dod.getRandomManufacturer());
        long count = Manufacturer.countManufacturers();
        Assert.assertTrue("Counter for 'Manufacturer' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ManufacturerIntegrationTest.testFindManufacturer() {
        Manufacturer obj = dod.getRandomManufacturer();
        Assert.assertNotNull("Data on demand for 'Manufacturer' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Manufacturer' failed to provide an identifier", id);
        obj = Manufacturer.findManufacturer(id);
        Assert.assertNotNull("Find method for 'Manufacturer' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Manufacturer' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ManufacturerIntegrationTest.testFindAllManufacturers() {
        Assert.assertNotNull("Data on demand for 'Manufacturer' failed to initialize correctly", dod.getRandomManufacturer());
        long count = Manufacturer.countManufacturers();
        Assert.assertTrue("Too expensive to perform a find all test for 'Manufacturer', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Manufacturer> result = Manufacturer.findAllManufacturers();
        Assert.assertNotNull("Find all method for 'Manufacturer' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Manufacturer' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ManufacturerIntegrationTest.testFindManufacturerEntries() {
        Assert.assertNotNull("Data on demand for 'Manufacturer' failed to initialize correctly", dod.getRandomManufacturer());
        long count = Manufacturer.countManufacturers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Manufacturer> result = Manufacturer.findManufacturerEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Manufacturer' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Manufacturer' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ManufacturerIntegrationTest.testFlush() {
        Manufacturer obj = dod.getRandomManufacturer();
        Assert.assertNotNull("Data on demand for 'Manufacturer' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Manufacturer' failed to provide an identifier", id);
        obj = Manufacturer.findManufacturer(id);
        Assert.assertNotNull("Find method for 'Manufacturer' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyManufacturer(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Manufacturer' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ManufacturerIntegrationTest.testMergeUpdate() {
        Manufacturer obj = dod.getRandomManufacturer();
        Assert.assertNotNull("Data on demand for 'Manufacturer' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Manufacturer' failed to provide an identifier", id);
        obj = Manufacturer.findManufacturer(id);
        boolean modified =  dod.modifyManufacturer(obj);
        Integer currentVersion = obj.getVersion();
        Manufacturer merged = (Manufacturer)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Manufacturer' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ManufacturerIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Manufacturer' failed to initialize correctly", dod.getRandomManufacturer());
        Manufacturer obj = dod.getNewTransientManufacturer(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Manufacturer' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Manufacturer' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Manufacturer' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ManufacturerIntegrationTest.testRemove() {
        Manufacturer obj = dod.getRandomManufacturer();
        Assert.assertNotNull("Data on demand for 'Manufacturer' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Manufacturer' failed to provide an identifier", id);
        obj = Manufacturer.findManufacturer(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Manufacturer' with identifier '" + id + "'", Manufacturer.findManufacturer(id));
    }
    
}
