// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.MerchantSource;
import com.lela.data.domain.entity.MerchantSourceDataOnDemand;
import com.lela.data.domain.entity.MerchantSourceIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MerchantSourceIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MerchantSourceIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MerchantSourceIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MerchantSourceIntegrationTest: @Transactional;
    
    @Autowired
    MerchantSourceDataOnDemand MerchantSourceIntegrationTest.dod;
    
    @Test
    public void MerchantSourceIntegrationTest.testCountMerchantSources() {
        Assert.assertNotNull("Data on demand for 'MerchantSource' failed to initialize correctly", dod.getRandomMerchantSource());
        long count = MerchantSource.countMerchantSources();
        Assert.assertTrue("Counter for 'MerchantSource' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MerchantSourceIntegrationTest.testFindMerchantSource() {
        MerchantSource obj = dod.getRandomMerchantSource();
        Assert.assertNotNull("Data on demand for 'MerchantSource' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MerchantSource' failed to provide an identifier", id);
        obj = MerchantSource.findMerchantSource(id);
        Assert.assertNotNull("Find method for 'MerchantSource' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'MerchantSource' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MerchantSourceIntegrationTest.testFindAllMerchantSources() {
        Assert.assertNotNull("Data on demand for 'MerchantSource' failed to initialize correctly", dod.getRandomMerchantSource());
        long count = MerchantSource.countMerchantSources();
        Assert.assertTrue("Too expensive to perform a find all test for 'MerchantSource', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<MerchantSource> result = MerchantSource.findAllMerchantSources();
        Assert.assertNotNull("Find all method for 'MerchantSource' illegally returned null", result);
        Assert.assertTrue("Find all method for 'MerchantSource' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MerchantSourceIntegrationTest.testFindMerchantSourceEntries() {
        Assert.assertNotNull("Data on demand for 'MerchantSource' failed to initialize correctly", dod.getRandomMerchantSource());
        long count = MerchantSource.countMerchantSources();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<MerchantSource> result = MerchantSource.findMerchantSourceEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'MerchantSource' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'MerchantSource' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MerchantSourceIntegrationTest.testFlush() {
        MerchantSource obj = dod.getRandomMerchantSource();
        Assert.assertNotNull("Data on demand for 'MerchantSource' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MerchantSource' failed to provide an identifier", id);
        obj = MerchantSource.findMerchantSource(id);
        Assert.assertNotNull("Find method for 'MerchantSource' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMerchantSource(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'MerchantSource' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MerchantSourceIntegrationTest.testMergeUpdate() {
        MerchantSource obj = dod.getRandomMerchantSource();
        Assert.assertNotNull("Data on demand for 'MerchantSource' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MerchantSource' failed to provide an identifier", id);
        obj = MerchantSource.findMerchantSource(id);
        boolean modified =  dod.modifyMerchantSource(obj);
        Integer currentVersion = obj.getVersion();
        MerchantSource merged = (MerchantSource)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'MerchantSource' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MerchantSourceIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'MerchantSource' failed to initialize correctly", dod.getRandomMerchantSource());
        MerchantSource obj = dod.getNewTransientMerchantSource(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'MerchantSource' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'MerchantSource' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'MerchantSource' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MerchantSourceIntegrationTest.testRemove() {
        MerchantSource obj = dod.getRandomMerchantSource();
        Assert.assertNotNull("Data on demand for 'MerchantSource' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MerchantSource' failed to provide an identifier", id);
        obj = MerchantSource.findMerchantSource(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'MerchantSource' with identifier '" + id + "'", MerchantSource.findMerchantSource(id));
    }
    
}
