// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.MerchantCategory;
import com.lela.data.domain.entity.MerchantCategoryDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect MerchantCategoryDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MerchantCategoryDataOnDemand: @Component;
    
    private Random MerchantCategoryDataOnDemand.rnd = new SecureRandom();
    
    private List<MerchantCategory> MerchantCategoryDataOnDemand.data;
    
    public MerchantCategory MerchantCategoryDataOnDemand.getNewTransientMerchantCategory(int index) {
        MerchantCategory obj = new MerchantCategory();
        setCategory(obj, index);
        setDateCreated(obj, index);
        setDateModified(obj, index);
        setEnableOffers(obj, index);
        setMerchant(obj, index);
        return obj;
    }
    
    public void MerchantCategoryDataOnDemand.setDateCreated(MerchantCategory obj, int index) {
        Date dateCreated = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateCreated(dateCreated);
    }
    
    public void MerchantCategoryDataOnDemand.setDateModified(MerchantCategory obj, int index) {
        Date dateModified = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateModified(dateModified);
    }
    
    public void MerchantCategoryDataOnDemand.setEnableOffers(MerchantCategory obj, int index) {
        Boolean enableOffers = Boolean.TRUE;
        obj.setEnableOffers(enableOffers);
    }
    
    public MerchantCategory MerchantCategoryDataOnDemand.getSpecificMerchantCategory(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        MerchantCategory obj = data.get(index);
        Long id = obj.getId();
        return MerchantCategory.findMerchantCategory(id);
    }
    
    public MerchantCategory MerchantCategoryDataOnDemand.getRandomMerchantCategory() {
        init();
        MerchantCategory obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return MerchantCategory.findMerchantCategory(id);
    }
    
    public boolean MerchantCategoryDataOnDemand.modifyMerchantCategory(MerchantCategory obj) {
        return false;
    }
    
    public void MerchantCategoryDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = MerchantCategory.findMerchantCategoryEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'MerchantCategory' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<MerchantCategory>();
        for (int i = 0; i < 10; i++) {
            MerchantCategory obj = getNewTransientMerchantCategory(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
