// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.MerchantSourceType;
import com.lela.data.domain.entity.MerchantSourceTypeDataOnDemand;
import com.lela.data.domain.entity.MerchantSourceTypeIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MerchantSourceTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MerchantSourceTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MerchantSourceTypeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MerchantSourceTypeIntegrationTest: @Transactional;
    
    @Autowired
    MerchantSourceTypeDataOnDemand MerchantSourceTypeIntegrationTest.dod;
    
    @Test
    public void MerchantSourceTypeIntegrationTest.testCountMerchantSourceTypes() {
        Assert.assertNotNull("Data on demand for 'MerchantSourceType' failed to initialize correctly", dod.getRandomMerchantSourceType());
        long count = MerchantSourceType.countMerchantSourceTypes();
        Assert.assertTrue("Counter for 'MerchantSourceType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MerchantSourceTypeIntegrationTest.testFindMerchantSourceType() {
        MerchantSourceType obj = dod.getRandomMerchantSourceType();
        Assert.assertNotNull("Data on demand for 'MerchantSourceType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MerchantSourceType' failed to provide an identifier", id);
        obj = MerchantSourceType.findMerchantSourceType(id);
        Assert.assertNotNull("Find method for 'MerchantSourceType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'MerchantSourceType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MerchantSourceTypeIntegrationTest.testFindAllMerchantSourceTypes() {
        Assert.assertNotNull("Data on demand for 'MerchantSourceType' failed to initialize correctly", dod.getRandomMerchantSourceType());
        long count = MerchantSourceType.countMerchantSourceTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'MerchantSourceType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<MerchantSourceType> result = MerchantSourceType.findAllMerchantSourceTypes();
        Assert.assertNotNull("Find all method for 'MerchantSourceType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'MerchantSourceType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MerchantSourceTypeIntegrationTest.testFindMerchantSourceTypeEntries() {
        Assert.assertNotNull("Data on demand for 'MerchantSourceType' failed to initialize correctly", dod.getRandomMerchantSourceType());
        long count = MerchantSourceType.countMerchantSourceTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<MerchantSourceType> result = MerchantSourceType.findMerchantSourceTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'MerchantSourceType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'MerchantSourceType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MerchantSourceTypeIntegrationTest.testFlush() {
        MerchantSourceType obj = dod.getRandomMerchantSourceType();
        Assert.assertNotNull("Data on demand for 'MerchantSourceType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MerchantSourceType' failed to provide an identifier", id);
        obj = MerchantSourceType.findMerchantSourceType(id);
        Assert.assertNotNull("Find method for 'MerchantSourceType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMerchantSourceType(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'MerchantSourceType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MerchantSourceTypeIntegrationTest.testMergeUpdate() {
        MerchantSourceType obj = dod.getRandomMerchantSourceType();
        Assert.assertNotNull("Data on demand for 'MerchantSourceType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MerchantSourceType' failed to provide an identifier", id);
        obj = MerchantSourceType.findMerchantSourceType(id);
        boolean modified =  dod.modifyMerchantSourceType(obj);
        Integer currentVersion = obj.getVersion();
        MerchantSourceType merged = (MerchantSourceType)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'MerchantSourceType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MerchantSourceTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'MerchantSourceType' failed to initialize correctly", dod.getRandomMerchantSourceType());
        MerchantSourceType obj = dod.getNewTransientMerchantSourceType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'MerchantSourceType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'MerchantSourceType' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'MerchantSourceType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MerchantSourceTypeIntegrationTest.testRemove() {
        MerchantSourceType obj = dod.getRandomMerchantSourceType();
        Assert.assertNotNull("Data on demand for 'MerchantSourceType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MerchantSourceType' failed to provide an identifier", id);
        obj = MerchantSourceType.findMerchantSourceType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'MerchantSourceType' with identifier '" + id + "'", MerchantSourceType.findMerchantSourceType(id));
    }
    
}
