// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.ObjectIdSequence;
import com.lela.data.domain.entity.ObjectIdSequenceDataOnDemand;
import com.lela.data.domain.entity.ObjectIdSequenceIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ObjectIdSequenceIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ObjectIdSequenceIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ObjectIdSequenceIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ObjectIdSequenceIntegrationTest: @Transactional;
    
    @Autowired
    ObjectIdSequenceDataOnDemand ObjectIdSequenceIntegrationTest.dod;
    
    @Test
    public void ObjectIdSequenceIntegrationTest.testCountObjectIdSequences() {
        Assert.assertNotNull("Data on demand for 'ObjectIdSequence' failed to initialize correctly", dod.getRandomObjectIdSequence());
        long count = ObjectIdSequence.countObjectIdSequences();
        Assert.assertTrue("Counter for 'ObjectIdSequence' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ObjectIdSequenceIntegrationTest.testFindObjectIdSequence() {
        ObjectIdSequence obj = dod.getRandomObjectIdSequence();
        Assert.assertNotNull("Data on demand for 'ObjectIdSequence' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ObjectIdSequence' failed to provide an identifier", id);
        obj = ObjectIdSequence.findObjectIdSequence(id);
        Assert.assertNotNull("Find method for 'ObjectIdSequence' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ObjectIdSequence' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ObjectIdSequenceIntegrationTest.testFindAllObjectIdSequences() {
        Assert.assertNotNull("Data on demand for 'ObjectIdSequence' failed to initialize correctly", dod.getRandomObjectIdSequence());
        long count = ObjectIdSequence.countObjectIdSequences();
        Assert.assertTrue("Too expensive to perform a find all test for 'ObjectIdSequence', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ObjectIdSequence> result = ObjectIdSequence.findAllObjectIdSequences();
        Assert.assertNotNull("Find all method for 'ObjectIdSequence' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ObjectIdSequence' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ObjectIdSequenceIntegrationTest.testFindObjectIdSequenceEntries() {
        Assert.assertNotNull("Data on demand for 'ObjectIdSequence' failed to initialize correctly", dod.getRandomObjectIdSequence());
        long count = ObjectIdSequence.countObjectIdSequences();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ObjectIdSequence> result = ObjectIdSequence.findObjectIdSequenceEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ObjectIdSequence' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ObjectIdSequence' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ObjectIdSequenceIntegrationTest.testFlush() {
        ObjectIdSequence obj = dod.getRandomObjectIdSequence();
        Assert.assertNotNull("Data on demand for 'ObjectIdSequence' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ObjectIdSequence' failed to provide an identifier", id);
        obj = ObjectIdSequence.findObjectIdSequence(id);
        Assert.assertNotNull("Find method for 'ObjectIdSequence' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyObjectIdSequence(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ObjectIdSequence' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ObjectIdSequenceIntegrationTest.testMergeUpdate() {
        ObjectIdSequence obj = dod.getRandomObjectIdSequence();
        Assert.assertNotNull("Data on demand for 'ObjectIdSequence' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ObjectIdSequence' failed to provide an identifier", id);
        obj = ObjectIdSequence.findObjectIdSequence(id);
        boolean modified =  dod.modifyObjectIdSequence(obj);
        Integer currentVersion = obj.getVersion();
        ObjectIdSequence merged = (ObjectIdSequence)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ObjectIdSequence' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ObjectIdSequenceIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ObjectIdSequence' failed to initialize correctly", dod.getRandomObjectIdSequence());
        ObjectIdSequence obj = dod.getNewTransientObjectIdSequence(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ObjectIdSequence' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ObjectIdSequence' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ObjectIdSequence' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ObjectIdSequenceIntegrationTest.testRemove() {
        ObjectIdSequence obj = dod.getRandomObjectIdSequence();
        Assert.assertNotNull("Data on demand for 'ObjectIdSequence' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ObjectIdSequence' failed to provide an identifier", id);
        obj = ObjectIdSequence.findObjectIdSequence(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ObjectIdSequence' with identifier '" + id + "'", ObjectIdSequence.findObjectIdSequence(id));
    }
    
}
