// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.PrimaryColor;
import com.lela.data.domain.entity.PrimaryColorDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect PrimaryColorDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PrimaryColorDataOnDemand: @Component;
    
    private Random PrimaryColorDataOnDemand.rnd = new SecureRandom();
    
    private List<PrimaryColor> PrimaryColorDataOnDemand.data;
    
    public PrimaryColor PrimaryColorDataOnDemand.getNewTransientPrimaryColor(int index) {
        PrimaryColor obj = new PrimaryColor();
        setDateCreated(obj, index);
        setDateModified(obj, index);
        setHex(obj, index);
        setPrimaryColorName(obj, index);
        setRgbCode(obj, index);
        return obj;
    }
    
    public void PrimaryColorDataOnDemand.setDateCreated(PrimaryColor obj, int index) {
        Date dateCreated = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateCreated(dateCreated);
    }
    
    public void PrimaryColorDataOnDemand.setDateModified(PrimaryColor obj, int index) {
        Date dateModified = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateModified(dateModified);
    }
    
    public void PrimaryColorDataOnDemand.setHex(PrimaryColor obj, int index) {
        String hex = "hex_" + index;
        if (hex.length() > 32) {
            hex = hex.substring(0, 32);
        }
        obj.setHex(hex);
    }
    
    public void PrimaryColorDataOnDemand.setPrimaryColorName(PrimaryColor obj, int index) {
        String primaryColorName = "primaryColorName_" + index;
        if (primaryColorName.length() > 255) {
            primaryColorName = primaryColorName.substring(0, 255);
        }
        obj.setPrimaryColorName(primaryColorName);
    }
    
    public void PrimaryColorDataOnDemand.setRgbCode(PrimaryColor obj, int index) {
        String rgbCode = "rgbCode_" + index;
        if (rgbCode.length() > 32) {
            rgbCode = rgbCode.substring(0, 32);
        }
        obj.setRgbCode(rgbCode);
    }
    
    public PrimaryColor PrimaryColorDataOnDemand.getSpecificPrimaryColor(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        PrimaryColor obj = data.get(index);
        Long id = obj.getId();
        return PrimaryColor.findPrimaryColor(id);
    }
    
    public PrimaryColor PrimaryColorDataOnDemand.getRandomPrimaryColor() {
        init();
        PrimaryColor obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return PrimaryColor.findPrimaryColor(id);
    }
    
    public boolean PrimaryColorDataOnDemand.modifyPrimaryColor(PrimaryColor obj) {
        return false;
    }
    
    public void PrimaryColorDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = PrimaryColor.findPrimaryColorEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'PrimaryColor' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<PrimaryColor>();
        for (int i = 0; i < 10; i++) {
            PrimaryColor obj = getNewTransientPrimaryColor(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
