// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.ProductDetailPartValue;
import com.lela.data.domain.entity.ProductDetailPartValueDataOnDemand;
import com.lela.data.domain.entity.ProductDetailPartValueIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProductDetailPartValueIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProductDetailPartValueIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProductDetailPartValueIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ProductDetailPartValueIntegrationTest: @Transactional;
    
    @Autowired
    ProductDetailPartValueDataOnDemand ProductDetailPartValueIntegrationTest.dod;
    
    @Test
    public void ProductDetailPartValueIntegrationTest.testCountProductDetailPartValues() {
        Assert.assertNotNull("Data on demand for 'ProductDetailPartValue' failed to initialize correctly", dod.getRandomProductDetailPartValue());
        long count = ProductDetailPartValue.countProductDetailPartValues();
        Assert.assertTrue("Counter for 'ProductDetailPartValue' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProductDetailPartValueIntegrationTest.testFindProductDetailPartValue() {
        ProductDetailPartValue obj = dod.getRandomProductDetailPartValue();
        Assert.assertNotNull("Data on demand for 'ProductDetailPartValue' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductDetailPartValue' failed to provide an identifier", id);
        obj = ProductDetailPartValue.findProductDetailPartValue(id);
        Assert.assertNotNull("Find method for 'ProductDetailPartValue' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ProductDetailPartValue' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProductDetailPartValueIntegrationTest.testFindAllProductDetailPartValues() {
        Assert.assertNotNull("Data on demand for 'ProductDetailPartValue' failed to initialize correctly", dod.getRandomProductDetailPartValue());
        long count = ProductDetailPartValue.countProductDetailPartValues();
        Assert.assertTrue("Too expensive to perform a find all test for 'ProductDetailPartValue', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ProductDetailPartValue> result = ProductDetailPartValue.findAllProductDetailPartValues();
        Assert.assertNotNull("Find all method for 'ProductDetailPartValue' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ProductDetailPartValue' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProductDetailPartValueIntegrationTest.testFindProductDetailPartValueEntries() {
        Assert.assertNotNull("Data on demand for 'ProductDetailPartValue' failed to initialize correctly", dod.getRandomProductDetailPartValue());
        long count = ProductDetailPartValue.countProductDetailPartValues();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ProductDetailPartValue> result = ProductDetailPartValue.findProductDetailPartValueEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ProductDetailPartValue' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ProductDetailPartValue' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProductDetailPartValueIntegrationTest.testFlush() {
        ProductDetailPartValue obj = dod.getRandomProductDetailPartValue();
        Assert.assertNotNull("Data on demand for 'ProductDetailPartValue' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductDetailPartValue' failed to provide an identifier", id);
        obj = ProductDetailPartValue.findProductDetailPartValue(id);
        Assert.assertNotNull("Find method for 'ProductDetailPartValue' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProductDetailPartValue(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ProductDetailPartValue' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProductDetailPartValueIntegrationTest.testMergeUpdate() {
        ProductDetailPartValue obj = dod.getRandomProductDetailPartValue();
        Assert.assertNotNull("Data on demand for 'ProductDetailPartValue' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductDetailPartValue' failed to provide an identifier", id);
        obj = ProductDetailPartValue.findProductDetailPartValue(id);
        boolean modified =  dod.modifyProductDetailPartValue(obj);
        Integer currentVersion = obj.getVersion();
        ProductDetailPartValue merged = (ProductDetailPartValue)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ProductDetailPartValue' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProductDetailPartValueIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ProductDetailPartValue' failed to initialize correctly", dod.getRandomProductDetailPartValue());
        ProductDetailPartValue obj = dod.getNewTransientProductDetailPartValue(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ProductDetailPartValue' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ProductDetailPartValue' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ProductDetailPartValue' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProductDetailPartValueIntegrationTest.testRemove() {
        ProductDetailPartValue obj = dod.getRandomProductDetailPartValue();
        Assert.assertNotNull("Data on demand for 'ProductDetailPartValue' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductDetailPartValue' failed to provide an identifier", id);
        obj = ProductDetailPartValue.findProductDetailPartValue(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ProductDetailPartValue' with identifier '" + id + "'", ProductDetailPartValue.findProductDetailPartValue(id));
    }
    
}
