// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.ProductDetailAttributeValueType;
import com.lela.data.domain.entity.ProductDetailAttributeValueTypeDataOnDemand;
import com.lela.data.domain.entity.ProductDetailAttributeValueTypeIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProductDetailAttributeValueTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProductDetailAttributeValueTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProductDetailAttributeValueTypeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ProductDetailAttributeValueTypeIntegrationTest: @Transactional;
    
    @Autowired
    ProductDetailAttributeValueTypeDataOnDemand ProductDetailAttributeValueTypeIntegrationTest.dod;
    
    @Test
    public void ProductDetailAttributeValueTypeIntegrationTest.testCountProductDetailAttributeValueTypes() {
        Assert.assertNotNull("Data on demand for 'ProductDetailAttributeValueType' failed to initialize correctly", dod.getRandomProductDetailAttributeValueType());
        long count = ProductDetailAttributeValueType.countProductDetailAttributeValueTypes();
        Assert.assertTrue("Counter for 'ProductDetailAttributeValueType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProductDetailAttributeValueTypeIntegrationTest.testFindProductDetailAttributeValueType() {
        ProductDetailAttributeValueType obj = dod.getRandomProductDetailAttributeValueType();
        Assert.assertNotNull("Data on demand for 'ProductDetailAttributeValueType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductDetailAttributeValueType' failed to provide an identifier", id);
        obj = ProductDetailAttributeValueType.findProductDetailAttributeValueType(id);
        Assert.assertNotNull("Find method for 'ProductDetailAttributeValueType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ProductDetailAttributeValueType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProductDetailAttributeValueTypeIntegrationTest.testFindAllProductDetailAttributeValueTypes() {
        Assert.assertNotNull("Data on demand for 'ProductDetailAttributeValueType' failed to initialize correctly", dod.getRandomProductDetailAttributeValueType());
        long count = ProductDetailAttributeValueType.countProductDetailAttributeValueTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'ProductDetailAttributeValueType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ProductDetailAttributeValueType> result = ProductDetailAttributeValueType.findAllProductDetailAttributeValueTypes();
        Assert.assertNotNull("Find all method for 'ProductDetailAttributeValueType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ProductDetailAttributeValueType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProductDetailAttributeValueTypeIntegrationTest.testFindProductDetailAttributeValueTypeEntries() {
        Assert.assertNotNull("Data on demand for 'ProductDetailAttributeValueType' failed to initialize correctly", dod.getRandomProductDetailAttributeValueType());
        long count = ProductDetailAttributeValueType.countProductDetailAttributeValueTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ProductDetailAttributeValueType> result = ProductDetailAttributeValueType.findProductDetailAttributeValueTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ProductDetailAttributeValueType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ProductDetailAttributeValueType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProductDetailAttributeValueTypeIntegrationTest.testFlush() {
        ProductDetailAttributeValueType obj = dod.getRandomProductDetailAttributeValueType();
        Assert.assertNotNull("Data on demand for 'ProductDetailAttributeValueType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductDetailAttributeValueType' failed to provide an identifier", id);
        obj = ProductDetailAttributeValueType.findProductDetailAttributeValueType(id);
        Assert.assertNotNull("Find method for 'ProductDetailAttributeValueType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProductDetailAttributeValueType(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ProductDetailAttributeValueType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProductDetailAttributeValueTypeIntegrationTest.testMergeUpdate() {
        ProductDetailAttributeValueType obj = dod.getRandomProductDetailAttributeValueType();
        Assert.assertNotNull("Data on demand for 'ProductDetailAttributeValueType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductDetailAttributeValueType' failed to provide an identifier", id);
        obj = ProductDetailAttributeValueType.findProductDetailAttributeValueType(id);
        boolean modified =  dod.modifyProductDetailAttributeValueType(obj);
        Integer currentVersion = obj.getVersion();
        ProductDetailAttributeValueType merged = (ProductDetailAttributeValueType)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ProductDetailAttributeValueType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProductDetailAttributeValueTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ProductDetailAttributeValueType' failed to initialize correctly", dod.getRandomProductDetailAttributeValueType());
        ProductDetailAttributeValueType obj = dod.getNewTransientProductDetailAttributeValueType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ProductDetailAttributeValueType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ProductDetailAttributeValueType' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ProductDetailAttributeValueType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProductDetailAttributeValueTypeIntegrationTest.testRemove() {
        ProductDetailAttributeValueType obj = dod.getRandomProductDetailAttributeValueType();
        Assert.assertNotNull("Data on demand for 'ProductDetailAttributeValueType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductDetailAttributeValueType' failed to provide an identifier", id);
        obj = ProductDetailAttributeValueType.findProductDetailAttributeValueType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ProductDetailAttributeValueType' with identifier '" + id + "'", ProductDetailAttributeValueType.findProductDetailAttributeValueType(id));
    }
    
}
