// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.ReviewProvider;
import com.lela.data.domain.entity.ReviewProviderDataOnDemand;
import com.lela.data.domain.entity.ReviewProviderIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ReviewProviderIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ReviewProviderIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ReviewProviderIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ReviewProviderIntegrationTest: @Transactional;
    
    @Autowired
    ReviewProviderDataOnDemand ReviewProviderIntegrationTest.dod;
    
    @Test
    public void ReviewProviderIntegrationTest.testCountReviewProviders() {
        Assert.assertNotNull("Data on demand for 'ReviewProvider' failed to initialize correctly", dod.getRandomReviewProvider());
        long count = ReviewProvider.countReviewProviders();
        Assert.assertTrue("Counter for 'ReviewProvider' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ReviewProviderIntegrationTest.testFindReviewProvider() {
        ReviewProvider obj = dod.getRandomReviewProvider();
        Assert.assertNotNull("Data on demand for 'ReviewProvider' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ReviewProvider' failed to provide an identifier", id);
        obj = ReviewProvider.findReviewProvider(id);
        Assert.assertNotNull("Find method for 'ReviewProvider' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ReviewProvider' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ReviewProviderIntegrationTest.testFindAllReviewProviders() {
        Assert.assertNotNull("Data on demand for 'ReviewProvider' failed to initialize correctly", dod.getRandomReviewProvider());
        long count = ReviewProvider.countReviewProviders();
        Assert.assertTrue("Too expensive to perform a find all test for 'ReviewProvider', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ReviewProvider> result = ReviewProvider.findAllReviewProviders();
        Assert.assertNotNull("Find all method for 'ReviewProvider' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ReviewProvider' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ReviewProviderIntegrationTest.testFindReviewProviderEntries() {
        Assert.assertNotNull("Data on demand for 'ReviewProvider' failed to initialize correctly", dod.getRandomReviewProvider());
        long count = ReviewProvider.countReviewProviders();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ReviewProvider> result = ReviewProvider.findReviewProviderEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ReviewProvider' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ReviewProvider' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ReviewProviderIntegrationTest.testFlush() {
        ReviewProvider obj = dod.getRandomReviewProvider();
        Assert.assertNotNull("Data on demand for 'ReviewProvider' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ReviewProvider' failed to provide an identifier", id);
        obj = ReviewProvider.findReviewProvider(id);
        Assert.assertNotNull("Find method for 'ReviewProvider' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyReviewProvider(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ReviewProvider' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ReviewProviderIntegrationTest.testMergeUpdate() {
        ReviewProvider obj = dod.getRandomReviewProvider();
        Assert.assertNotNull("Data on demand for 'ReviewProvider' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ReviewProvider' failed to provide an identifier", id);
        obj = ReviewProvider.findReviewProvider(id);
        boolean modified =  dod.modifyReviewProvider(obj);
        Integer currentVersion = obj.getVersion();
        ReviewProvider merged = (ReviewProvider)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ReviewProvider' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ReviewProviderIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ReviewProvider' failed to initialize correctly", dod.getRandomReviewProvider());
        ReviewProvider obj = dod.getNewTransientReviewProvider(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ReviewProvider' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ReviewProvider' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ReviewProvider' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ReviewProviderIntegrationTest.testRemove() {
        ReviewProvider obj = dod.getRandomReviewProvider();
        Assert.assertNotNull("Data on demand for 'ReviewProvider' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ReviewProvider' failed to provide an identifier", id);
        obj = ReviewProvider.findReviewProvider(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ReviewProvider' with identifier '" + id + "'", ReviewProvider.findReviewProvider(id));
    }
    
}
