// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lela.data.domain.entity;

import com.lela.data.domain.entity.Subdepartment;
import com.lela.data.domain.entity.SubdepartmentDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect SubdepartmentDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SubdepartmentDataOnDemand: @Component;
    
    private Random SubdepartmentDataOnDemand.rnd = new SecureRandom();
    
    private List<Subdepartment> SubdepartmentDataOnDemand.data;
    
    public Subdepartment SubdepartmentDataOnDemand.getNewTransientSubdepartment(int index) {
        Subdepartment obj = new Subdepartment();
        setDateCreated(obj, index);
        setDateModified(obj, index);
        setDirty(obj, index);
        setSubdepartmentName(obj, index);
        setSubdepartmentStatus(obj, index);
        setSubdepartmentURLName(obj, index);
        return obj;
    }
    
    public void SubdepartmentDataOnDemand.setDateCreated(Subdepartment obj, int index) {
        Date dateCreated = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateCreated(dateCreated);
    }
    
    public void SubdepartmentDataOnDemand.setDateModified(Subdepartment obj, int index) {
        Date dateModified = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateModified(dateModified);
    }
    
    public void SubdepartmentDataOnDemand.setDirty(Subdepartment obj, int index) {
        Boolean dirty = Boolean.TRUE;
        obj.setDirty(dirty);
    }
    
    public void SubdepartmentDataOnDemand.setSubdepartmentName(Subdepartment obj, int index) {
        String subdepartmentName = "subdepartmentName_" + index;
        obj.setSubdepartmentName(subdepartmentName);
    }
    
    public void SubdepartmentDataOnDemand.setSubdepartmentStatus(Subdepartment obj, int index) {
        String subdepartmentStatus = "subdepartmentStatus_" + index;
        obj.setSubdepartmentStatus(subdepartmentStatus);
    }
    
    public void SubdepartmentDataOnDemand.setSubdepartmentURLName(Subdepartment obj, int index) {
        String subdepartmentURLName = "subdepartmentURLName_" + index;
        obj.setSubdepartmentURLName(subdepartmentURLName);
    }
    
    public Subdepartment SubdepartmentDataOnDemand.getSpecificSubdepartment(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Subdepartment obj = data.get(index);
        Long id = obj.getId();
        return Subdepartment.findSubdepartment(id);
    }
    
    public Subdepartment SubdepartmentDataOnDemand.getRandomSubdepartment() {
        init();
        Subdepartment obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Subdepartment.findSubdepartment(id);
    }
    
    public boolean SubdepartmentDataOnDemand.modifySubdepartment(Subdepartment obj) {
        return false;
    }
    
    public void SubdepartmentDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Subdepartment.findSubdepartmentEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Subdepartment' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Subdepartment>();
        for (int i = 0; i < 10; i++) {
            Subdepartment obj = getNewTransientSubdepartment(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
